### ISSUE TITLE
can't define actions for terminal

### ISSUE THREAD

**Issue by lotard** [knausj85/knausj_talon#100]
I can't put my finger on it, but some action definitions don't work in terminal.talon. For example:
`action(app.tab_open):
	key(cmd-t)`
This does not work, Talon doesn't even recognize it (it hears 'near tab'). In contrast this works perfectly:
`new tab:
	key(cmd-t)`
Note that I have no problem with 'new window', which is defined through an action.I'm just putting it out there and hope it would be useful. ``

**Comment by knausj85** [comment]
@lotard 
Is the correct app/bundle name of your terminal app in the tabs file? 

https://github.com/knausj85/knausj_talon/blob/master/misc/tabs.talon

FWIW, I have a command that dumps the focused app stuff to the console for debugging. It's *probably* best to use the bundle on OS X. Note I don't have this command in the repro currently.

`debug app:
 print(app.name())
 print(app.bundle())
 print(app.executable())`

You can also tell if the tab commands are available via the "help active" for the focused application. You should see "tabs" in the list somewhere, if available.

**Comment by lotard** [comment]
@knausj85 
You got it! It only had /terminal/, not Terminal. Now it works.

**Comment by knausj85** [comment]
Great, feel free to submit a PR with the addition of Terminal. I believe /terminal/ is for some linux terminals.
