### ISSUE TITLE
Builtin actions for "clear word left" and similar commands

### ISSUE THREAD

**Issue by gsingh93** [knausj85/knausj_talon#1015]
The current implementation of "clear word left" (and related `<verb> word <direction>` commands) uses `edit.extend_word_left()`:
```talon
clear word left:
    edit.extend_word_left()
    edit.delete()
```
 Many terminals don't implement any text selection functionality with the keyboard, so `edit.extend_word_left()` will not work in these cases. This means we need to reimplement this command for each terminal like. For example, on macOS this would look like:
 ```talon
 clear word left:
    key("cmd+backspace")
```

The issue here is that it may become difficult to standardize on the command phrase if we keep implementing it like this. It may be better to have some builtin action like `edit.clear_word_left` that could be implemented by terminals, so they could reuse the same command phrase instead.

Alternatively, a separate module (is that the right term?) could be defined like `term.clear_word_left`, and the "clear word left" command could be defined for terminals using this. This has the downside that we still duplicate the command definition twice, but the benefit that we don't clutter a builtin module like `edit` with every combination of verb and direction (i.e. clear word right, cut word left, etc.).

**Comment by rntz** [comment]
#1034 added these, should we consider this issue resolved?

**Comment by gsingh93** [comment]
Yeah, we can close this now.
