### ISSUE TITLE
Jetbrains: cannot work with two instances of the same IDE

### ISSUE THREAD

**Issue by Gotos** [knausj85/knausj_talon#1074]
I often have multiple instances of PyCharm or Webstorm running when working on services that depend on each other (and sometimes just because I want to look up how I or my coworkers solved a certain problem in another project).

However, it seems to me that I cannot use the Jetbrains commands when running, say, two instances of Webstorm. That makes sense to me, as the port for the communication is hard coded per IDE. If I run the same IDE twice, obviously only one of them can use that port for communication.

I'm not sure how to best solve this problem. If I understand the code of the Jetbrains integration correctly, the IDE plugin and Talon do exchange a nonce via a temp file already. Maybe a port could be set in a similar fashion? That, of course, would require coordinated code changes here and for https://github.com/anonfunc/intellij-voicecode, but I'm not sure if that could even be avoided at all when attempting to fix this issue/implement this feature request.

If this is a desired feature and would make a good first issue despite spanning two projects, I'd be interested in having a look at implementing this feature myself. I'm unsure if my suggested approach would be the best one though - or if I'm maybe even just missing something that'd cover my use case already.

**Comment by Gotos** [comment]
I think this is actually related to https://github.com/anonfunc/intellij-voicecode/issues/1. Only just saw that there's an issue open for that.

**Comment by Gotos** [comment]
Disregard that. I had other issues with my config. Apparently this just works, now that the voicecode plugin is actually enabled :smile: 

I assume if I have multiple Webstorm projects open (in different windows), under the hood it's still just one instance of the IDE running and that's why it works? Anyway, it's working like a charm now, so I'm gonna close this :slightly_smiling_face:

**Comment by auscompgeek** [comment]
I actually legitimately need to run two instances of the same JetBrains IDE sometimes (specifically two different versions of IntelliJ Ultimate Edition), which doesn't work in this setup, so we should probably reopen this.
