### ISSUE TITLE
Select word issues

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#1084]
### Background
`select_word()` in its current state has some major edge cases due to the fact that it treats all characters next to the carat the same way regardless of which characters they are.

The key issues I've seen are:
1. Accidental selection of symbols rather than words
2. Word selection breaking if the caret is before a new line.

### Examples
**If the caret is next to any punctuation, `select_word()` may select the punctuation instead of the word (depending on the app you're in).**

Here are some examples from the `TextEdit` app, `Evernote` app, and the `Github` web editor.

1. ![image](https://user-images.githubusercontent.com/9077250/210577873-7368efeb-7c82-4475-b071-37103c260d6d.png)
3. ![image](https://user-images.githubusercontent.com/9077250/210581542-dec1e408-c5c5-4ebe-95e7-c1b923f80dcd.png)
4. ![image](https://user-images.githubusercontent.com/9077250/210581418-4c005e7e-0764-420a-ae26-f74d3c4650e9.png)
5. ![image](https://user-images.githubusercontent.com/9077250/210581473-8d3a3ada-32c7-4d73-9f71-3cb196b2deff.png)
6. ![image](https://user-images.githubusercontent.com/9077250/210588494-b0a4dfb6-1028-415d-bb4d-fb12663d62a2.png)
7. ![image](https://user-images.githubusercontent.com/9077250/210588509-2b5e4174-43eb-4e46-9f20-34fb3e751979.png)

**If the caret is on the last character in a line, `select_word()` may break and not select anything useful (depending on the app you're in).**

Here is an example from the Github web editor:

1. ![image](https://user-images.githubusercontent.com/9077250/210592047-2c8e742b-2543-481d-802d-f7740af4f09c.png)
2. ![image](https://user-images.githubusercontent.com/9077250/210592161-82e25752-121f-434b-b187-58319dc913c4.png)

**Comment by rntz** [comment]
I wasn't able to replicate this behavior in my testing, although it may be relevant that I'm on Ventura. I tried TextEdit and the GitHub editor in firefox, as well as normal text boxes in Safari.

**Comment by rntz** [comment]
@nriley was able to replicate it in Chrome on Monterey, however.

**Comment by splondike** [comment]
MR aiming to fix these has been merged, closing this out.
