### ISSUE TITLE
Conflict between `"dropdown <number>"` and Cursorless `"drop down <number>"`

### ISSUE THREAD

**Issue by pokey** [knausj85/knausj_talon#1087]
The recently introduced `"dropdown <number>"` commands (https://github.com/knausj85/knausj_talon/pull/881) conflict with the cursorless command `"drop down <number>"`, where `"drop"` is the action to insert an empty line above a target, and `"down <number>"` refers to the line `<number>` lines below the cursor.

Maybe we should pick one of the other proposed alternatives (https://github.com/knausj85/knausj_talon/pull/881#issuecomment-1279867764)?

Alternately, if we change `"dropdown <number>"` to `"drop down <number>"`, I believe that will cause Talon to favour the knausj command

**Comment by rntz** [comment]
Reopen if you think this conflict will cause problems for cursorless users; I'm not adverse to renaming the command if so.
