### ISSUE TITLE
add command for retrieving user.system_path itself in a terminal

### ISSUE THREAD

**Issue by DonnerWolfBach** [knausj85/knausj_talon#1088]
I really like the system to store the paths via a csv introduced in #802 as a result of #785 , but I would like to have a way to get these paths without the "cd" in front. Thus I propose adding this in terminal.talon under `go <user.system_path>: insert('cd "{system_path}"\n ls\n')`:
```
path <user.system_path>: insert('"{system_path}"')
# or
<user.system_path> path: insert('"{system_path}"')
```
Is any of these better or worse for working with talon (like impacting performance)?

**Comment by DonnerWolfBach** [comment]
Btw, I am already working on the pull request, but I'll have to cleanup some other things first

**Comment by DonnerWolfBach** [comment]
Pull request is done + removed "<> path" as suggested by splondike

**Comment by splondike** [comment]
PR has been merged, closing this out.
