### ISSUE TITLE
Import of eye_zoom_mouse, eye_mouse was removed from mouse.py, but the references to them are still present in code and raise errors

### ISSUE THREAD

**Issue by ziemus** [knausj85/knausj_talon#1094]
The import of eye_zoom_mouse and eye_mouse was removed from mouse.py 4 days ago but the references to them are still present in code. It raises errors in the talon log. It also breaks mouse functionality, like continuous scrolling.

**Comment by knausj85** [comment]
Oops, this was an embarrassing merge error on my part; I can fix this tomorrow if no one beats me to it

**Comment by knausj85** [comment]
This has been addressed in #1095
