### ISSUE TITLE
'Phones that' command with two options should automatically select the second option

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#1098]
**Context**
When you run `phones that`, and you get two options with the current word being one of the two, we should default to selecting the second option (the word that isn't the current word) to save the user time. 

In other words, we shouldn't show this UI:
![image](https://user-images.githubusercontent.com/9077250/214274165-411c2f40-f6f7-4774-995f-1421a5885a5d.png)

In most cases the alternative word is probably what the user wants and this will save them a lot of trouble. 

In the rarer cases where the alternative word isn't what they were looking for, it is just as easy to run `phones that` again to automatically switch back as it is to run `phones hide` with the current implementation.

**Comment by rntz** [comment]
fixed by #1157
