### ISSUE TITLE
Call to undeclared `dictation_peek`

### ISSUE THREAD

**Issue by wenkokke** [knausj85/knausj_talon#1124]
My warning log is filling up with
```
WARNING actions: skipped because they have no matching declaration: (user.dictation_peek)
```
What is causing this?

**Comment by wenkokke** [comment]
Could Talon be discarding the definition of `dictation_peek` as its typing is too complex?
```python
def dictation_peek(left: bool, right: bool) -> tuple[Optional[str], Optional[str]]:
```

**Comment by nriley** [comment]
What Talon version are you using? I don't get that with the current Rust beta and I'm not having any issues with the definition.

```python
% rg dictation_peek
plugin/talon_draft_window/draft_talon_helpers.py
77:    def dictation_peek(left, right):

core/text/text_and_dictation.py
388:            before, after = actions.user.dictation_peek(need_left, need_right)
399:    def dictation_peek(left: bool, right: bool) -> tuple[Optional[str], Optional[str]]:
411:        dictation_peek() is intended for use before inserting text, so it may
```

Also would recommend you restart Talon if you haven't — sometimes I find the cached declarations get confused with the autoreloader.

**Comment by wenkokke** [comment]
Something went wrong during my knausj upgrade, so `dictation_peek` was actually missing locally.
