### ISSUE TITLE
help overlay not movable 

### ISSUE THREAD

**Issue by stevenqzhang** [knausj85/knausj_talon#131]
all of my help overlays and command histories are not movable. this is something that's a known issue ?

running the latest version of the talon beta. macos 10.14.6

**Comment by knausj85** [comment]
This is a limitation of Talon currently; it's planned to make it draggable.

In the interm, you can tweak the positions in code as-needed by looking for and modifying the `@imgui.open` calls

e.g.,
https://github.com/knausj85/knausj_talon/blob/18115d2f5e9f90c01decdc591a3b44362e17bbf2/code/help.py#L59
