### ISSUE TITLE
FEATURE: extended dictation

### ISSUE THREAD

**Issue by auphofBSF** [knausj85/knausj_talon#132]
Dictation mode functions , but at the moment is not best in class. What talon does give us is the ability to switch to a command mode  and do editing that I believe is getting to best of class. 
Whilst we can possibly look to integrate with a best of class Dictation Executor this is probably a bigger project. Maybe there is some low hanging fruit in enabling Talon dictation mode to use some of the noise commands two switch temporarily back to `command mode` and then automatically back into `dictation mode` 

My proposal is  if the mouse click `chif` is heard then switched to command mode and if a pause of X seconds of no voice  happens then switch  back to dictation mode.

It would be nice to display in a future Talon desktop widget which mode Talon is in.

Any other thoughts?

**Comment by fidgetingbits** [comment]
As someone that doesn't use dictation mode much (<1% of my day) or mouse (<10%), I'm just curious what type situations/use cases you're envisioning where you'd want command mode enabled just for a small amount of time based on your mouse click? 

The widget I agree will be useful.

**Comment by auphofBSF** [comment]
The webspeech ,that @lunixbochs has released to beta improves dictation mode greatly. 
I probably work 50/50 in dictation and command mode. To elaborate on the use-case for easy switching to command mode for a period. 

> Having dictated a few paragraphs, I want to rapidly go and edit, my first action is to move the cursor to a spot and then issue voice commands (chiff | duke,  select *, delete | say, etc) 
 I move the cursor with a mouse or hand on tablet but utter noises for the clicks (painful to click). 

The proposed widget would be initiated by a mouse click (verbal or real) it will remain in command mode whilst commands are being uttered, let say 2secs without commands and then automatically (without saying dictation mode) continue in dictation.  If command mode is issued at any stage that takes precedence.  Ideally an indicator is showing as to what mode we are in. 
The complexity I think is detecting the mouse click events, I will be willing to give the implementation a go , great way to learn more about talon. Any other suggestions welcome

**Comment by knausj85** [comment]
Interesting. I don’t necessarily think this would be a good fit for this depot out-of-the-box, but I’d gladly take a peek. It strikes me as something users would want to opt into.

**Comment by knausj85** [comment]
I'm going to close this one since I'm not sure it's a good fit, and there's been no movement.
