### ISSUE TITLE
[subject][action] vs [action][subject] standard for commands?

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#148]
> there is an inconsistency in the repo with regards to how generic command order is approached across the repo, specifically with the order of [subject][action] vs [action][subject]. The most obvious example is earlier in this review you recommended using the file save, which follows the [subject][action] order. However, with the generic tab commands they all support the [action][subject] order. I also mix up the order situationally within the vim grammars, but it's making me wonder if we should try to standardize on one over the other, since I know you don't want to have duplicate ways of saying commands in your own repo.

>I personally prefer [subject][action] in general because I can speak the subject that I want to interact with and then say what I want to do with it and it helps me think about what commands I actually going to give. I also think it correlates well to command-line stuff, where we say the number of the command first, and then the sub command. That said I guess it will rely depend on the user as to what order seems most intuitive though. I can move this discussion into a separate issue if you prefer.

**Comment by brxck** [comment]
I will make a personal vote for object-verb ordering, which is how I have things set up in my personal fork. They should definitely be made consistent either way.

**Comment by knausj85** [comment]
I'm going to close this to declutter; this is included in the 'Guidelines for contributions' these days, too.
