### ISSUE TITLE
Programming language detection for Jetbrains on Mac

### ISSUE THREAD

**Issue by JeongJuhyeon** [knausj85/knausj_talon#152]
This seems like it'd already be known if others were having the same issue, so maybe there's something specific to my device but the new programming language detection introduced in [this commit](https://github.com/knausj85/knausj_talon/commit/bba1b56156eb264477ef73344751f91804f38957#diff-5ed633abfa6ec97c8ba70e118a200320) doesn't work for PyCharm for me on Mac. Both "file_extension" and "file_name" are blank. For reference, the regex-based method it replaced still works fine so I'm back to that one for now.

**Comment by knausj85** [comment]
@JeongJuhyeon 
Sorry for the inconvenience, the logic is now ide-specific since the regex was just too fragile across platforms/programs. 

Something like this just needs to be added to the jetbrains
https://github.com/knausj85/knausj_talon/blob/master/apps/vscode/vscode.py

**Comment by JeongJuhyeon** [comment]
Okay, Ill give it a try!
Would falling back on the regex if the other method fails until we have implementations for more IDEs be too messy?

**Comment by knausj85** [comment]
It was really just too fragile to be useful cross-platform/cross-app. We'd fix it for one platform or program, and another would break. I'd rather it do nothing for an application by default than break. It's also one reason I added support to force enable languages via commands.

You could probably get away with using the regex in the jetbrains-specific implementation. I have no objections to that, but it's probably worth doing it without the regex to make it more robust.

**Comment by JeongJuhyeon** [comment]
Fair enough 👍

**Comment by splondike** [comment]
Closing issue.
