### ISSUE TITLE
Investigate generic grammar for apps with window splitting

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#158]
- tmux, vscode, notepad++ support various window split functionality. Maybe it makes sense to move this out of ide and into its own thing to be activated by a tag?

**Comment by fidgetingbits** [comment]
seems sane. vim supports this as well, but one interesting scenario will be people running vim inside of tmux lol.

**Comment by knausj85** [comment]
@ma-anwar & @fidgetingbits - FYI https://github.com/knausj85/knausj_talon/commit/7cf99123a487f644c6f96fd50ee6c4de83e9ac18

**Comment by fidgetingbits** [comment]
cool thanks. will plan to add that to my vim stuff
