### ISSUE TITLE
Consider generic code snippet grammar

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#160]
Similar to the code.py actions, consider ide- and language-agnostic snippet actions

```
def snippet_state_if():
    """Inserts if statement"""
```

generic_snippets.talon

```
tag: generic_snippet
_
snippet if: snippet_if()
snippet function: snippet_function()
snippet try: snippet_try()
```

**Comment by knausj85** [comment]
yeah, this is meant to leverage the ide's snippets for the reason you mentioned (tabbing thru). i described my intent rather poorly.

e.g.,
```
app: vscode
code.language: python
-
tag(): generic_snippet

action(snippet_state_if): 
    #insert vscode-specific python snippet here
```

let's see how portable the grammar can be between ides. half-baked thought for now.

**Comment by knausj85** [comment]
FWIW, I settled on using captures for this.

https://github.com/knausj85/knausj_talon/commit/1e4eea598e795c77da960da4e0880baddd4fa2f7

**Comment by fidgetingbits** [comment]
looks nice thanks. will see about changing my vim stuff to use this now too when i get a chance
