### ISSUE TITLE
use standard python code formatter

### ISSUE THREAD

**Issue by dwiel** [knausj85/knausj_talon#171]
Do you have thoughts on using a standard python code formatter like `black`? There are a few reasons for putting all python code through such a tool.

1) Using a tool like `black` makes editing code by voice significantly easier. You can dictate code in a nasty format and with no spaces, etc. Once you are done, you can just let your editor/formatter fix everything for you with a single command or on every save
2) It makes it easier to keep a codebase like this being edited by multiple people in the same style for easier reading and contributing

One issue with this tool is that if I start using it on my code, any PR I make will include all kinds of formatting changes as well which is undesirable. I would be happy to make a PR which runs the entire code base through such a formatter, just let me know.

**Comment by fidgetingbits** [comment]
I am using black at the moment for this same reason and basically anything I send pull  requests for I just include the black changes. definitely be in favor of everyone moving to black :D

**Comment by knausj85** [comment]
yeah, this is a good call. I think fidget brought it up some time ago

I'm fine with blackening all the things.

**Comment by dwiel** [comment]
Thanks!
