### ISSUE TITLE
Dictation mode / sentence formatter puts a space after the last word before punctuation.

### ISSUE THREAD

**Issue by nickeubank** [knausj85/knausj_talon#173]
when in dictation mode ,  if one attempts to use punctuation , talon adds spaces between the last word and punctuation marks .  

As demonstrated above .

**Comment by knausj85** [comment]
I can't reproduce this one - what OS and engine are you using?

**Comment by nickeubank** [comment]
Catalina 10.15.5

Here's Talon: 

![image](https://user-images.githubusercontent.com/9683693/88442222-bcf91e80-cde1-11ea-9755-f8061885c941.png)

And Dragon is 6.0.8. 

Maybe it's a weird timing thing? When I (self-consciously) try to recreate it, it only happens for the middle comma -- here's a recording...

[Screen Recording 2020-07-24 at 7.17.33 PM.zip](https://github.com/knausj85/knausj_talon/files/4974576/Screen.Recording.2020-07-24.at.7.17.33.PM.zip)

**Comment by knausj85** [comment]
The commands here are very simple -
https://github.com/knausj85/knausj_talon/blob/master/modes/dictation_mode.talon#L7
so I suspect the key_wait setting might need to be adjusted for impacted applications in its .talon file to prevent it from missing simulated keystrokes.

```
settings():
    key_wait = 1.4
```

I forget what it’s in (ms?), but it defaults to 1.

**Comment by nickeubank** [comment]
Thank! I'll give that a shot.

**Comment by nickeubank** [comment]
unfortunately ,  still seem to be having problems . even after i change the delay to two milliseconds , I'm still getting the behavior you see here . 

[Screen Recording 2020-07-28 at 7.29.54 AM.zip](https://github.com/knausj85/knausj_talon/files/4987992/Screen.Recording.2020-07-28.at.7.29.54.AM.zip)

my file: 

![image](https://user-images.githubusercontent.com/9683693/88660259-64a57380-d0a4-11ea-8189-1c5279afc1b1.png)


And my extra file (suggested in beta chat for formatting):

![image](https://user-images.githubusercontent.com/9683693/88660315-7ab33400-d0a4-11ea-973c-6924f7574414.png)

**Comment by knausj85** [comment]
@nickeubank Oops, I didn't mean to close this automatically. 

After further testing, I believe the autoformatter is the best approach for addessing this one. Could you try this?
https://github.com/knausj85/knausj_talon/commit/9383b50814f963f1ffcc772d8384d94fce9435f9

**Comment by nickeubank** [comment]
Thank you! This seems to be working much better!  the only thing I'm noticing is that the problem still exists when in "command mode" space using either "say" or "phase":

[Screen Recording 2020-07-29 at 8.46.50 AM.zip](https://github.com/knausj85/knausj_talon/files/4994920/Screen.Recording.2020-07-29.at.8.46.50.AM.zip)

Would it make sense to add the same formatting to those two calls?

**Comment by knausj85** [comment]
Oops. Hmm, I’m not sure the state machine approach is appropriate for say/phrase.

**Comment by nickeubank** [comment]
Is it adding a space, or missing a backspace meant to delete the gap before the punctuation?

**Comment by knausj85** [comment]
There's a few things at play here:

1. Anchored commands
2. The user.text capture

**Anchored commands**
```
phrase <user.text>$: insert(user.text)
phrase <user.text> over: insert(user.text)
```

The first command is anchored ($), so it continues until there's a pause, rather attempting anything that might be a command. "comma" is a command, but is not processed due to the anchor in your example.

The second command, with over, is not anchored, so something like "say this is a test over comma" does the correct thing. 


**user.text capture**
The capture does a string conversion on the capture, some splitting and a join, resulting in the extra space in the anchored example.

https://github.com/knausj85/knausj_talon/blob/master/code/vocabulary.py#L46

Few potential options here. 
- Don't anchor the command. This caused me grief in the past, but boils down to personal preference.
- Do some extra work in the capture - dragon specific. (w2l would provide the word comma). Not sure how I feel about this at the moment.

e.g.,
```
punctuation = {
    ".": ".",
    "?": "?",
    "!": "!",
    ",": ",",
    ":": ":",
    ";": ";",
}

@mod.capture(rule="(<user.vocabulary> | <phrase>)+")
def text(m) -> str:
    # todo: use actions.dicate.parse_words for better dragon support once supported
    # print(actions.dictate.parse_words(m.phrase))

    words = str(m).split(" ")
    i = 0
    while i < len(words):
        word = remove_dragon_junk(words[i])
        if i > 0 and word in punctuation:
            words[i - 1] = words[i - 1] + word
            words.pop(i)
        else:
            words[i] = word
            i += 1

    return " ".join(words)
```

**Comment by knausj85** [comment]
After poking at the api a bit more, this fix works reasonably well. 

https://github.com/knausj85/knausj_talon/commit/f13905294e01a006c1352d1e2fefdf26bfc926fc

**Comment by nickeubank** [comment]
amazing! thanks so much! this seems to be working much better.

**Comment by nickeubank** [comment]
One latent bug hiding in here:  `'`  i don't think is being recognized as punctuation - they keep getting a space when I'm trying to write possessives (e.g. "people 's").

**Comment by knausj85** [comment]
The latest has a fix for if you were dictating "people's" with dragon.

**Comment by nickeubank** [comment]
Yup! :) Thanks so much. Sorry I'm not great at patching myself -- more data scientist than software engineer.

**Comment by knausj85** [comment]
No problem, thanks for reporting these.
