### ISSUE TITLE
alphabetically order lists where possible

### ISSUE THREAD

**Issue by fidgetingbits** [knausj85/knausj_talon#175]
This issue is in the vein of #171, but one small thing I often do with my own lists is constantly makes sure alphabetized so that it's easier to quickly update them manually but also find a relevant entry while scanning with my eyes (vs searching), etc. examples would be things like the various formats in `formatters.py` ([yours](https://github.com/knausj85/knausj_talon/blob/master/code/formatters.py#L104) vs [mine](https://github.com/fidgetingbits/knausj_talon/blob/master/code/formatters.py#L114)) , things in `abbreviate.py`, etc. 

so it be worth considering to favor alphabetically ordered lists to make managing the code even easier/faster. might be kind of annoying in some editors, but in vim it is trivial so I can always do it and send pull requests if necessary. also sometimes alphabetizing doesn't make sense because things are categorized into smaller groups, but just in general it would be nice because even if they're grouped they could be alphabetized within the group.

this is obviously way less impactful then black changes, and possibly more subjective preference (would make merging easier for me sometimes lol) so of course feel free to close and ignore as needed :D

**Comment by knausj85** [comment]
Yeah, I think this is a sensible default. Good call.
