### ISSUE TITLE
`i` not being capitalized in dictation / speak?

### ISSUE THREAD

**Issue by nickeubank** [knausj85/knausj_talon#187]
When I'm using dictation mode, i am finding that the first person singular is not being properly capitalized, as illustrated in this sentence.  Compound constructions like "I'm" or "I've" work, but not a single i.

i am finding this happens whether i am using the command "say" or using dictation mode.

I'm really confused about this because it seems like there's code that should make the substitution:

![image](https://user-images.githubusercontent.com/9683693/89057802-42be2200-d32c-11ea-9138-5ea6ff5171b5.png)

**Comment by knausj85** [comment]
This is fixed on the latest version. I neglected to call `replace_words` in the capture.

Note Dragon doesn't actually provide "i" here, it provides "i\pronoun," so the parse_words and replace_words stuff is needed. 

On the other hand, wav2letter captures just "i", and the `user.vocabularly` capture maps it to "I".
