### ISSUE TITLE
Cannot dictate a variable named "point"

### ISSUE THREAD

**Issue by jeheydorn** [knausj85/knausj_talon#190]
With the Windows beta of Talon, and with Dragon NaturallySpeaking, when I try to  write the word "point" using Talon formatters, it becomes '.'. For example:
"camel point" -> .
"hammer point" -> . 
"word point" -> .

I was hoping this was something I could change in the Python config files in ~/talon, but I can't seem to find where it's happening. I did a grep search of my ~/talon folder and I don't see anything causing this. Particularly it's not configured in keys.py, nor formatters.py.  When formatters are called, point has already been converted to '.'.

I don't think this is caused by Dragon because when Talon is disabled, with Dragon in dictation and command mode, if I say point it writes "point". In Dragon's command mode if I say point, it writes nothing, as expected since that's not a Dragon command and Talon was off.

Any help would be appreciated. Being able to write variables and types named "point" is important to me because I am trying to work on code involving two-dimensional graphics. Having "point" convert to "." when writing floating point numbers is great, but I'm hoping to disable that conversion in formatters. I know I can spell out "point", but it's twice as many syllables. I also don't want to modify the formatters to convert '.' back to "point" because then I couldn't use "dot" with formatters.

**Comment by knausj85** [comment]
Hmm, "point" is allegedly a dragon thing for "." for "all dialects" per https://www.nuance.com/products/help/dragon/dragon-for-mac6/enx/Content/Dictating/Dictating_punctuation.htm

There's nothing in my repo that maps point to "."

You can try map point to point in vocab maybe?
https://github.com/knausj85/knausj_talon/blob/17279a22020a65ae832fae247265a967082f96ad/code/vocabulary.py#L14

**Comment by jeheydorn** [comment]
That worked. Thanks

**Comment by knausj85** [comment]
@jeheydorn - Feel free to submit a PR for this, I doubt you'll be the only one to run into it. Closing the issue.
