### ISSUE TITLE
How to set variable mouse scroll speed for different programs?

### ISSUE THREAD

**Issue by ym-han** [knausj85/knausj_talon#191]
I'm thinking of trying to set different mouse scroll speeds for different programs. That is, I currently have something like the following for mouse_scroll_down:

  
```
def mouse_scroll_down_continuous(delta: float = 50):
        global continuous_scoll_mode
        continuous_scoll_mode = "scroll down continuous"
        mouse_scroll(delta)()
        if scroll_job is None:
            start_scroll()

        gui_wheel.show()

````

and I would like to add a few conditionals to the function to hard-code in certain values for `delta` for certain programs. How do I (programmatically) check what app is active?  And do you think this would be a good way to go about doing things?

Eventually, though, it would be nice to be able to have some of these parameters get set automatically by some machine learning algorithm.

**Comment by knausj85** [comment]
Hmm, there are few options for this. One already exists on the tip.
https://github.com/knausj85/knausj_talon/blob/master/code/mouse.py#L71

In a .talon file, you can tinker with a few settings per context (OS, app, whatever).
```
app: someAppHere
-
settings():
    user.setting_mouse_continuous_scroll_amount = 60
    user.setting_mouse_wheel_down_amount = 80
```

In the above, 60 will be used for continuous scrolling when _showAppHere_ has focus. The tradeoff, for OSes that have scroll-follows-mouse (e.g., windows), is that if you scroll in a window that isn't currently focused, it will also use that speed.


If you really want to get fancy, you'd have to determine which window is receiving the scroll. Apps on Mac and Linux are z-ordered iirc, so you could iterate thru the list and try to determine which window the cursor position falls within. I tend to think this is overkill in practice.

**Comment by ym-han** [comment]
Oh nice thanks! I hadn't noticed that new functionality.

**Comment by knausj85** [comment]
Closing this one, let me know if there’s any issues.
