### ISSUE TITLE
talon.exe uses 20% of CPU and makes system slow to respond, while throwing errors continuously

### ISSUE THREAD

**Issue by jeheydorn** [knausj85/knausj_talon#197]
I'm using talon beta on Windows 10 with Dragon 15.3. When I start up talon, after it initializes and connects to Dragon, it uses about 15 – 23% of my CPU (about one for core), and causes the computer to become slow to respond. The mouse becomes shaky, and applications can take several seconds to respond sometimes.

I ran talon_console.exe, and it constantly gives these errors which might be related (or they might not be, see my later discussion):

2020-08-19 11:59:31 WARNING actions: implementations skipped because they have no matching declaration: (user.password_show, user.password_duplicate, user.password_new, user.password_delete, user.password_edit, user.password_fill)
2020-08-19 11:59:31 WARNING actions: implementations skipped because they have no matching declaration: (user.password_show, user.password_duplicate, user.password_new, user.password_delete, user.password_edit, user.password_fill)
2020-08-19 11:59:31 ERROR cb error topic="win_focus" cb=<function update_maps at 0x0000000009ECEAF8>
   18:                  <stdlib>/threading.py:890|
   17:                  <stdlib>/threading.py:926|
   16:                  <stdlib>/threading.py:870|
   15:             talon\windows\winevents.py:172|
   14:            talon\scripting\dispatch.py:98 |
   13:            talon\scripting\dispatch.py:133|
   12:            talon\scripting\dispatch.py:124|
   11:                talon\scripting\rctx.py:199|
   10: ------------------------------------------# 'win_focus' main:_on_event()
    9:                    talon\windows\ui.py:79 |
    8:            talon\scripting\dispatch.py:98 |
    7:            talon\scripting\dispatch.py:133|
    6:            talon\scripting\dispatch.py:126|
    5:                talon\scripting\rctx.py:201|
    4: ------------------------------------------# 'win_focus' user.knausj_talon.code.file_manager:update_maps()
    3: ------------------------------------------# stack splice
    2:                talon\scripting\rctx.py:199|
    1: user\knausj_talon\code\file_manager.py:486| ctx.lists.update(lists)
AttributeError: 'DictionaryMeta' object has no attribute 'update'
2020-08-19 11:59:31 WARNING actions: implementations skipped because they have no matching declaration: (user.password_show, user.password_duplicate, user.password_new, user.password_delete, user.password_edit, user.password_fill)
2

It's very possible these errors are not related to the high CPU usage. I have another windows 10 machine with the same number of cores on which I see talon consume on 3 – 10% of the CPU, and talent_console.exe gives the same errors on that machine. The only relevant difference I think of is that machine is on Dragon 15 (not 15.3).

I'm hoping this is just something wrong with my setup. Please let me know if it is. In my talon home folder, under talon\user, has the latest version of  https://github.com/knausj85/knausj_talon, which I cloned a few minutes ago. My talon executable might be older - I don't know how to update it. I tried the "Check for updates…" option from the taskbar icon, but it doesn't seem to do anything.

**Comment by knausj85** [comment]
I think the there are a few issues:

1. Talon's out of date.

To update on Windows, you need to navigate to

`%appdata%\Talon\.venv\Scripts\`

and run `update.bat`. If you installed talon in Program Files, be sure to run update.bat as an admin

2. It looks like you're missing a few files from this folder. Actions have to be declared somewhere, and those are declared in password_manager.py
https://github.com/knausj85/knausj_talon/tree/master/apps/1password

For the CPU usage, do you have any of the imgui things open - history, help, formatters?

**Comment by jeheydorn** [comment]
Thanks.  Updating talon resolved the errors I was seeing in talen_console_.exe,  and reduced cpu usage to 6%-13%.

If I may bug you with another question, I can't seem to dictate a ':' (colon) when talon and Dragon are in command mode. Could you point me in the direction I should be looking to figure out why? In keys.py I see "colon": ":", is defined, and other symbols,  such as ';' work fine. I tried mapping "colon" to ":" in mapping_vocabulary in vocabulary.py, but it didn't help. When I dictate a colon, in dragon's recognition history, it just says ???. I work around this by saying "word colon". If dragon or talon are in dictation mode, then I can dictate a ':' just fine.

**Comment by knausj85** [comment]
Oh, you’ll need to map the symbol colon to itself in keys.py for dragon most likely.

`“:” : “:”`

since that’s what dragon provides , rather than the word.

**Comment by jeheydorn** [comment]
That worked. Thanks
