### ISSUE TITLE
window management: `snap left`, `snap bottom right`, etc

### ISSUE THREAD

**Issue by dwiel** [knausj85/knausj_talon#217]
public talon implementation here: https://github.com/dwiel/talon_community/blob/master/misc/window_snap.py

**Comment by knausj85** [comment]
There's a PR for something similar that I held off on since neither Windows nor Linux have support for setting the rect yet.

https://github.com/knausj85/knausj_talon/pull/107

Maybe it's okay to keep it Mac-specific for now.
