### ISSUE TITLE
window management: `window move screen {number}`

### ISSUE THREAD

**Issue by dwiel** [knausj85/knausj_talon#218]
for moving a window to a different screen: https://github.com/dwiel/talon_community/blob/master/misc/window_snap.py

**Comment by jcaw** [comment]
I have a WIP implementation for this and #217 on my [window_snap](https://github.com/jcaw/knausj_talon/tree/window_snap) branch, but it's waiting on first-party support in Talon for window resizing on Windows & Linux. It may already work on Mac, but I can't test it yet.

**Comment by dwiel** [comment]
I've got this version as well. Which works on mac, not sure about others

https://github.com/knausj85/knausj_talon/compare/master...dwiel:master#diff-c8f5f3c289379630eff2dd117390ecbb

**Comment by dwiel** [comment]
Just saw your PR dont worry about my implementation
