### ISSUE TITLE
terminal: kubernetes

### ISSUE THREAD

**Issue by dwiel** [knausj85/knausj_talon#219]
implementation here:

- https://github.com/dwiel/talon_community/blob/master/apps/terminal.py#L222
- https://github.com/dwiel/talon_community/blob/master/apps/terminal.py#L361

**Comment by knausj85** [comment]
I think much of that is here?
https://github.com/knausj85/knausj_talon/tree/master/apps/kubectl

**Comment by dwiel** [comment]
Yeah, that is definitely a good start. Some commands missing include:

- cube get {resource} (and similar)
- cube detach

Maybe a few others
