### ISSUE TITLE
Becoming a real "community" repo

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#226]
This is just to discuss the possibility of adding a few direct contributors to the repo besides myself. I'm still poking a few other people, but ideally I'm hoping for 4 collaborators including myself.

The things I'm looking for help with:
1. Responding to issues and PRs.
2. If you have any specific areas or platform of expertise, e.g. jetbrains/vim or Mac/Linux, take some degree of "ownership" of those bits where feasible. 

**Collaborator guidelines**

- [ ] Take care of yourself and your health/needs first. Limit your time commitment to this effort.

- [ ] For "minor" fixes/improvements/bugs/new apps, you're free to contribute without any review

- [ ] For significant new development/refactoring you feel makes sense, it's likely still prudent to get a review from one of the other collaborators, or open a discussion as appropriate before committing your time?

**Potential guidelines for contributions (PR review, etc)**

- [ ] Any addition to the global grammar should be scrutinized a bit more thoroughly. The more specific a new context, the less scrutiny I typically apply.

- [ ] New grammars should follow the [subject][verb] standard where-ever possible.

- [ ] For Mac OS X, the bundle id should be used for defining app contexts, rather than the name. 

- [ ]  For Windows, both the friendly app name and exe name should be used for defining app contexts. For some people, the MUICache breaks.

- [ ] For new web apps, ensure the domain is used to minimize potential mismatches
https://github.com/knausj85/knausj_talon/blob/master/apps/web/window_titles.md

- [ ] New applications should support the appropriate 'generic' grammars where possible
```
generic_browser.talon
find_and_replace.talon
line_commands.talon
multiple_cursors.talon
snippets.talon
splits.talon
tabs.talon
```

- [ ] New programming languages should support the appropriate 'generic' grammars where possible as well
```
operators.talon
programming.talon
comment.talon
block_comment.talon
```

and should support the lists

```
user.code_functions
user.code_libraries
```

where appropriate. See e.g. csharp.py/csharp.talon. At least, until we come up with something better 👍

**Comment by knausj85** [comment]
@fidgetingbits & @dwiel 

A few preliminary thoughts on how this might work...

**Comment by dwiel** [comment]
Looks good to me. Maybe we can move these guidelines to the readme as well.

**Comment by knausj85** [comment]
@2hsea is open to helping out too.

- I won't add anyone until you give me an official "I'm in!" on here. I figure the minimum number of collaborators to make this workable is 4.
- For visibility, I'll probably be capping myself at ~2 hours / week starting 9/21. This will fluctuate with health and work/life commitments, of course - per the first collaborator guideline :)

**Comment by rntz** [comment]
I'm in.

Isn't there a standard way of matching for apps across different platforms now? There was some discussion of this on the slack earlier but I didn't follow it very closely.

**Comment by dwiel** [comment]
I'm in

**Comment by knausj85** [comment]
@rntz It's not standard across platforms, but the app is defined in python so it's standardized across all .talon files.

For things that don't really need their own .py yet, I've been defining them in 
https://github.com/knausj85/knausj_talon/blob/master/code/application_matches.py

For things that have their own .py anyway, they live there e.g.
https://github.com/knausj85/knausj_talon/blob/master/apps/vscode/vscode.py#L8

**Comment by fidgetingbits** [comment]
I'm in

**Comment by knausj85** [comment]
Excellent, I really appreciate this! Hopefully, it works out well.

I've added an initial section to the readme:
https://github.com/knausj85/knausj_talon#collaborators

**Comment by knausj85** [comment]
Figured I'd check-in to see how's it going. Any complaints or issues?

Seems to be working well, as far I can see.

**Comment by rntz** [comment]
Closing this to declutter our issues list. Happy holidays!
