### ISSUE TITLE
'command history' toggle causes talon crash

### ISSUE THREAD

**Issue by aceslowman** [knausj85/knausj_talon#227]
Using the talon linux beta 1488, the phrase 'command history' successfully displays the panel, but after toggling another panel, ie 'formatter help', the history panel becomes unable to move and Talon crashes when 'command history' is repeated to close the panel. 

The panel does work fine as long as other panels are not toggled.

Only relevant output in the console is:
`Segmentation fault (core dumped)`

Let me know if there is any other info that would be helpful!

**Comment by knausj85** [comment]
@aceslowman This sounds more like a Talon bug. I believe there's an issue with GPU rendering on linux, sometimes.

As a temporary workaround, try switching all these lines
`@imgui.open(software=False)`

to

`@imgui.open(software=True)`

**Comment by aceslowman** [comment]
Great, thanks!
