### ISSUE TITLE
simplify kubectl implementation

### ISSUE THREAD

**Issue by dwiel** [knausj85/knausj_talon#229]
The current kubernetes implementation looks like this:

```
# .talon
cube create: insert(user.kubectl_create())

# .py
    def kubectl_create() -> str:
        """Create a resource from a file or from stdin."""
        return f"{kubectl} create "
```

should this just be simplified to:

```
cube create: "kubectl create "
```

**Comment by knausj85** [comment]
I don't remember who contributed this, but they had some reason I can't recall. I'm fine with the above though.

**Comment by fidgetingbits** [comment]
if there's some other tool that people often use other than `kubectl` that effectively has the same arguments it might make sense? but I've never used it so I have no idea. definitely seem simpler to just have the suggested single straight now

**Comment by dwiel** [comment]
I've used it a bit, but dont know of any other. I guess we can simplify it if someone finds the time.
