### ISSUE TITLE
lists/dicts in vocabulary in separate json files for easier merging of changes to vocabulary.py

### ISSUE THREAD

**Issue by dwiel** [knausj85/knausj_talon#239]
As it stands, many refactors to `vocabulary.py` result in merge conflicts due to custom vocabulary defined. If these were instead read from json files, this would no longer be a problem.

**Comment by rntz** [comment]
good idea. I think we should be able to do something like what homophones.py does, and load them from csv files.

**Comment by dwiel** [comment]
Yeah, CSV works and has precedent 👍 I think jcaw might have some work in this direction as well

**Comment by dwiel** [comment]
Specifically, something standard would be best. CSV, Json, etc. That way people dont have to learn some new format, how do you escape commas? How do you use quotes? What about commas inside quotes? Just pick a standard and stick to it rather than invent yet another file format

**Comment by dwiel** [comment]
Also a reminder of `resource.open` which allows talon to do auto reloading on file changes.

**Comment by jcaw** [comment]
CSVs have the bonus that we can parse them line-by-line and ignore bad lines, whereas a JSON parse error will bring down the whole file.

I think if we do use CSV, we'll need to lay it out with headers:

```
| Word | Substitution (Optional) |
| ---- | ----------------------- |
| cash | cache                   |
| def  |                         |  <-- This will map to itself, "def": "def"
```

This could be a generic format that allows the user to define list contents in general. The only problem with CSV (and JSON) is that it doesn't support comments.

How would you want to handle words that need to be capitalized? 
- We could force the user to write out both forms
- We could have another CSV that just has one column, but that breaks the pattern of `spoken_form: optional_substitute`. 
- We could include the capitalized words in one column and perform some magic to map them when they're added to the substitition list. This seems confusing though.

**Comment by jcaw** [comment]
Hmm... What about this?

Additional words:

```
| Word(s) | Spoken Form (If Different) |
| ------- | -------------------------- |
| nmap    | enn map                    |
| def     |                            |
```

Then for capitalized:

```
| Replacement | Original (Optional) |
| ----------- | ------------------- |
| cache       | cash                |
| December    |                     |
```

**Comment by jcaw** [comment]
And for multiples:

```
| Word(s) | Spoken Form (If Different) |
| ------- | -------------------------- |
| nmap    |                            |
| nmap    | enn map                    |
| nmap    | N map                      |
```

Since the key is on the right, to maintain dict semantics we can just error out on rows where a non-empty spoken form is redefined.

**Comment by dwiel** [comment]
multiple files sound good to me, essentially replicating what is currently in vocabulary.py. Just to be clear though, I think we should use CSV format for now though, the header is okay:

```
output, spoken form
cache, cash
nmap, N map
```

**Comment by fidgetingbits** [comment]
this all looks good to me, will definitely make it easier to manage. I think using csv format is fine

**Comment by jcaw** [comment]
I've got an implementation working using the file format I described here, so it's no extra work to use that (probably less tbh, since it's just one format). I can do either approach.

@knausj85 @rntz (and anyone else), thoughts on preference? Two files in the structure above, or four files replicating the current structure?

**Comment by jcaw** [comment]
Another benefit of doing it that way is the system could be used anywhere we need to define a Talon list in a user file, and they'd all have the same basic format.

**Comment by rntz** [comment]
@jcaw I'm confused about your proposal. Your examples have a lot of formatting in them (`|` and `-`) – do you propose including that in the actual files, or is that merely to make the examples clearer? I would prefer a format closer to csv, pseudo-table formatting seems unnecessary and difficult to maintain over a large file.

My main concerns with csv are support for comments and dealing with leading and trailing white space or other special characters. Comments are easy enough to add, we can just use `#` at the beginning of the line. White space and special characters aren't an issue with any of our current use cases, so I think we can punt on that for now and add it later unless someone specifically wants to deal with it.

Is there a reason not to just use comments as headers?

I have no strong preference regarding having two files versus four files.

**Comment by jcaw** [comment]
I just drew the structure for visualisation, the format is a normal CSV:

```
Header 1,Header 2
value 1,key 1
value 2
value 3, key 3
```

Whitespace and special characters should work fine with CSV. Escaping is easy, you just use quotes: `normal value,"escaped, value"`. You only need to escape commas and quotes - padding is respected.

I'm against modifying vanilla CSVs to add comments. It's too unexpected. I think something like that would require an explicitly new format.

**Comment by rntz** [comment]
sounds good to me then, if somebody makes a PR for this I'd be happy to review/accept it :)

In fact, if we're going to be using vanilla csv I think there's a python module for that in the standard library: https://docs.python.org/3/library/csv.html

**Comment by knausj85** [comment]
sounds like everyone's on the same page, but FWIW I'd vote to keeping it simple & clean- 

(1) Use CSV; probably stick with vanilla CSV stuff since this is (presumably) a temporary solution until .talon has support for lists. Just document when/what we can.
(2) 4 files is probably the most intuitive for newbies, particularly with the differences between Dragon and w2l re: capitalization.
