### ISSUE TITLE
Move language modes into command mode specific file

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#270]
Currently the commands to enable languages are available in all modes.

https://github.com/knausj85/knausj_talon/blob/e487fe3e0b8a494ca3c416c1b813ef0dbd4249f1/modes/modes.talon#L32

Also, consider using tags instead of modes

**Comment by fidgetingbits** [comment]
I agree these shouldn't be accessible in all modes. I constantly sleep talon and these modes keep waking up while I'm in a meeting lol
 
being able to assert the tags that are only accessible in command mode seems best. I plan to move the windbg/gdb modes into just tags as well. this way it is likely easier to be able to also forcefully assign a tag assertion to some context, so say have vmware have c mode enabled even if talon doesn't know it's running an IDE inside, etc.

**Comment by ym-han** [comment]
How do we 'forcefully' assign tags? (I take it that you mean forcing tags on the fly in the same way that we might force modes on the fly with voice.) Is this possible right now?

**Comment by knausj85** [comment]
@ym-han I believe on a context object in .py you can do

```
ctx.tags = ['a', 'b', 'c']
```

to assert tags

**Comment by ym-han** [comment]
As in, we can use that to assert tags on the fly *with voice* in the way that we might say 'force <language name>' to assert lang modes? For some reason I was under the impression that that would only be possible with lang modes.

**Comment by knausj85** [comment]
Yeah, the action could just do something like this:

```
from talon import Module, Context
ctx = Context()
mod = Module()

  def code_set_language_mode(language: str):
        """Sets the active language mode, and disables extension matching"""
        ctx.tags = [language]
        forced_language = True
```

simplifying the logic quite a bit. It would save modes for other, more exotic purposes -- say, a math dictation mode or different spoken languages mode.

**Comment by ym-han** [comment]
Ahhh, thank you so much Jeff! 

I really should do a deep dive on the Talon API / folks' scripts soon...

**Comment by knausj85** [comment]
This seems good enough as-is, not really feeling the need to move to tags.
