### ISSUE TITLE
"welcome back" prints "go to sleep" in dication mode under W2L engine

### ISSUE THREAD

**Issue by beret** [knausj85/knausj_talon#300]
In W2L with dictation mode, every time I say welcome back I get “go to sleep” typed out, and listed in the command history. The logs don’t show any decodes for go to sleep, just welcome back.

I suspect this change in modes.talon triggered it, causing an engine.mimic call for "go to sleep" from engine.py but handled incorrectly in dictation mode.
https://github.com/knausj85/knausj_talon/commit/458543843c231cc34742cc560855d669420f68d9

Current git versions of scripts and Talon, no custom talon files in user.
I also tested using a 3 month old codebase and didn’t see this issue then.

**Comment by knausj85** [comment]
I opened an FR so we can determine the active engine. The behavior of `talon_mode` needs to vary based on the engine--it's currently written for Dragon.

**Comment by beret** [comment]
This resolves the issue, thank you!
