### ISSUE TITLE
this or that?

### ISSUE THREAD

**Issue by nriley** [knausj85/knausj_talon#311]
Noticed another inconsistency.

When you want to act on the selected text, most commands refer to the selection as "that"…except [symbols.talon](https://github.com/knausj85/knausj_talon/blob/e93773116087cc52120a41d3f4b14dd57d5f119f/text/symbols.talon#L46), which uses "this".

Does it make sense to change `this` to `that`, or is there some exception I'm missing?

**Comment by rntz** [comment]
I hadn't noticed those symbols.talon commands before. I'd prefer consistency and renaming them to use "that".

**Comment by nriley** [comment]
OK, sounds good to me :)
