### ISSUE TITLE
Canonical homophone is always the longest word 

### ISSUE THREAD

**Issue by beret** [knausj85/knausj_talon#315]
https://github.com/knausj85/knausj_talon/blob/ffeaa0269487510e99db11e7d8bcefe05157b135/code/homophones.py#L38

Per discussion in #help, phones is picking the longest word of a set as the canonical. Proposed alteration is `canonical_list.append(words[0])` and then sorting the sets of homophones by frequency and possibly length.

https://talonvoice.slack.com/archives/C7ENXA7C4/p1609792196126300

**Comment by rntz** [comment]
It seems like the reason this matters is that the canonical versions of each group get turned into `phones $WORD` commands, so it's important that the canonical words be ones that are recognised well, eg. "bite" is better recognised than "bight".

I wonder if there's some reason why the canonical one is chosen to be longest?

**Comment by fidgetingbits** [comment]
Something I was thinking about lately is if it would be good to have the homophones handler rewrite the csv entry after a selection is made, so the default match becomes whatever you last selected based on the assumption that it's what you frequently want. but the above has me wondering if we should write modified homophone lists to some secondary copy, so we can also track frequencies of all words in a per-user json file. then populate the selector window and default word used by talon (whenever a homophone is encountered) based on the content of json list, but still have the static list for initial distribution and populating the `phones` command with the canonical word. this may be suited for another issue though

**Comment by beret** [comment]
In the chat there is a word frequency list we could probably use for one-off sorting of a default list.

Caveat: I made the case to get the issue documented, but I don't really use phones functionality myself.

**Comment by rntz** [comment]
The word frequency list is at https://bochs.info/~aegis/popular-words.txt (for future reference in case it leaves slack history)

**Comment by lunixbochs** [comment]
This should be fixed by https://github.com/knausj85/knausj_talon/pull/318

**Comment by beret** [comment]
I'm going to close this as resolved for now. The plan on dynamic updating of phones priority is cool, and probably best addressed as a new broader issue IMHO.
