### ISSUE TITLE
folder structure in `apps` (super nitpicky, trivial thing)

### ISSUE THREAD

**Issue by ym-han** [knausj85/knausj_talon#322]
I noticed that the OS folders (`mac`, `linux`, etc) are currently at the same level as folders for (presumably) OS-independent apps like `jetbrains` and `vscode`. Here's a quick suggestion: how about putting the latter into a folder like `OS_independent`, so that the only folders at that level are that and the folders for the specific OSes? Right now it feels like a category mistake to me to have specific apps like `vscode` be at the same level as `mac` and `linux`.

**Comment by lunixbochs** [comment]
why not structure like this:

apps/slack/win.talon, apps/slack/linux.talon, apps/slack/mac.talon, apps/slack/slack.talon

**Comment by knausj85** [comment]
Alright, the migration of actions from talon -> python seems like a reasonable time to do something about this.

For multi-platform apps I was leaning towards:

```
chrome.talon # self-explanatory
chrome.py  # common stuff, action declarations and such
mac.py # mac-specific action implementations  etc+ app definition maybe
win.py # win-specific action implementations  etc + app definition maybe
```

It's sometimes handy to be able to quickly compare the actions for debugging purposes and such.

@pokey @splondike @rntz @dwiel

**Comment by pokey** [comment]
@knausj85 Those would all be in an `apps/chrome/` directory?

Seems reasonable to me

**Comment by knausj85** [comment]
Yeah, those would all be in an apps/chrome/ directory.

I guess the default app.talon / edit.talon implementations should probably be moved into 

```
code/app/mac.py 
code/app/win.py
```

Or something too.

I’m not a huge fan of the OS_Independent idea proposed in the original issue personally-I’d vote to either flatten (no platform subdirs in apps) or keep as-is. I’m not too picky about the folder structure, so speak now. 🤗

**Comment by rntz** [comment]
Are we sure that we'll never have platform-specific talon files? I think we currently do for Firefox, for example. ISTR we'd rather not name those things like `firefox/mac.talon` because of some interaction with the help system.

**Comment by knausj85** [comment]
There will very likely still be platform-specific commands, and `firefox_mac.talon` is still  reasonable. `/mac.py` (or something more explicit) is  just for action definitions that have to live in python, and don't interact with help.  

Generally, I believe most platform-specific Talon files are solely used for action definitions at the moment? Reality might be different in folks branches. Slack is an exception, at the moment.
