### ISSUE TITLE
Revert using software=True on linux

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#335]
Now that https://github.com/talonvoice/talon/issues/190 is fixed, we should be able to use imgui.open(software=False) by default everywhere again. I haven't tested this on my box yet, though.

**Comment by lunixbochs** [comment]
`software=` for both imgui and canvas is being deprecated in v0.1.5 fyi. I recommend just removing it. There is a replacement parameter, but I would prefer to not hardcode the backend type at call sites, so if there's an ongoing need for this I will look into a global setting.

**Comment by rntz** [comment]
Ok, I'll try just deleting them tonight and see whether I still have any issues.

**Comment by rntz** [comment]
Seems to work for me. Made a PR.

**Comment by rntz** [comment]
oh woops, looks like @knausj85 beat me to it :)
