### ISSUE TITLE
Navigating the cursor left or right to user specified points of interest. 

### ISSUE THREAD

**Issue by daanvdh** [knausj85/knausj_talon#341]
When I am on a line of text in any program, I want to be able to navigate to any symbol. I also want to be able to extend my current selection to include anything until a given Symbol left or right. 

We already have some advanced: navigation in "word_selection.talon". I propose to rename this file to "column_navigation.talon" and to extend it to contain the functionality proposed above. 

I have my initial implementatioon here: https://github.com/daanvdh/knausj_talon/edit/slave/apps/editor/navigation.talon

**Comment by knausj85** [comment]
reposting from slack:

since these are envisioned as all global commands, why not put them in generic editor?
I don’t necessarily see a good reason to separate these anymore, as it seems to just prevent people from finding them. ‘go back’ and stuff may not be a good fit, but we can deal with that later to get it in.

anything more advanced that requires specific application-level support could be under some appropriate tag

**Comment by daanvdh** [comment]
I'm fine with putting the commands in the Generic editor file. Should I still rename word_selection.py to column_navigation.py and include my code there?

**Comment by knausj85** [comment]
I would vote to go with generic_editor.py in this case

**Comment by daanvdh** [comment]
This can become a of code, but I see that that file does not exist yet. So then it's fine.

**Comment by daanvdh** [comment]
Working on this issue in https://github.com/daanvdh/talonTextNavigation

**Comment by knausj85** [comment]
these work really well thus far and are really, really handy

**Comment by daanvdh** [comment]
Yeah, still debating between "after/before" or "till/past" commands. Latest implementation works with regex, so can virtually search for anything. Planning to also create some select and delete implementations and also make a default implementation for the "select next". Anyone who wants to help out can join the given github repo, it's a separate repo only containing the navigation. Will be merged here eventually.

**Comment by knausj85** [comment]
I will spend some time on it tomorrow

I would personally vote for the below. 

```
go before
go after
```

which would make it consistent with the line commands, arrow commands and whatnot

**Comment by daanvdh** [comment]
Downside of that is that moving the cursor In the left direction is ambiguous for those statements. "Before" Only has meaning from a reference point, and from the command it's not clear if the reference point is the beginning of the sentence or the cursor location. With "till" It's clear that the reference point is the cursor location, another upside is that it's shorter.

**Comment by rntz** [comment]
I think most folks would expect "before" and after to mean *globally* before or after, i.e. "before plex" in the string "abxcd" means "ab|xcd" no matter whether we're running "left before plex" from the right edge of the line or running "go right before plex" from the left edge of the line.

**Comment by knausj85** [comment]
from playing around with this today, feels like we would very much benefit from variants that navigate to the left of the cursor as well. 

maybe there's room for both global and relative?

**Comment by rntz** [comment]
Uh, I think we must be talking about different things - I'm not sure what the <number> in your example could mean. Also I've realized that the terms *absolute* and *relative* are a bit vague here.

Here is what I would expect the following commands to do, using | to represent the cursor position:

"right before colon", "right until colon": move right until the cursor is left of the nearest colon. Eg. `a:b|c:d` becomes `a:bc|:d`.

"left before colon", "left past colon": move left until the cursor is left of the nearest colon. `a:b|c:d` becomes `a|:bc:d`.

"right after colon", "right past colon": move right until the cursor is right of the nearest colon. Eg. `a:b|c:d` becomes `a:bc:|d`.

"left after colon", "left until colon": move left until the cursor is right of the nearest colon. `a:b|c:d` becomes `a:|bc:d`.

**Comment by knausj85** [comment]
sorry, I screwed up my example since I was in a hurry. That is exactly what I would expect, but there are times where I have found myself wanting the "global" version from a quick try

```
#relative to the cursor on the line 
before cursor <user.unmodified_key>  [<number>]
after cursor <user.unmodified_key> [<number>]

#global to the line 
before <user.unmodified_key>  [<number>]
after <user.unmodified_key> [<number>]
```
 
for instance, navigating to  _ before 'mouth' from the | position below after dictating the line

```
and eye_zoom_mouth.zoom_mouse.state == eye_zoom_mouse.STATE_IDLE|
```

**Comment by rntz** [comment]
Ah, I see. Should be pretty easy to implement those in terms of the cursor-relative ones: just go to the start of the line first.

**Comment by daanvdh** [comment]
@rntz Thanks for the clear explanation, and yes this is what I meant. Before I wrote this code I also argued that before and after should be relative to the start of the line. But after using it I see that I mix up before and after a lot when going left. 

@knausj85 I disagree that there be a should separate statement for "global Number", You can simply say "home" before it. In your specific example I would want to use "left select mouth". I already implemented the statement for going to the right, not yet for going to the left.

**Comment by daanvdh** [comment]
Getting a bit stuck on the amount of different options that are useful for this type of navigation. How about I create one big method, and also one big Talon line That together handle everything. I'm thinking of something like this:
`<user.navigation_option> <user.direction> <user.cursor_location> <user.navigation_input> [<number>]:
	user.navigation(navigation_option, direction, cursor_location, navigation_input, number or  1)`
Example usage: 
`go left before comma`
I think this will be the most easy to extend, for instance with cases like "global number" That @knausj85 wants. This also prevents that we have to maintain a lot of interfaces that are currently accessible from Talon files.

**Comment by knausj85** [comment]
I think you're right re: using home - we don't need the global version for simplicity. 

```
<user.navigation_option> <user.direction> <user.cursor_location> <user.navigation_input> [<number>]: user.navigation(navigation_option, direction, cursor_location, navigation_input, number or 1)
```

I think the above obfuscates things a little bit too much for newbies, and it makes it rather difficult to customize the commands. I think the way you have written currently both code wise and command wise is superior

**Comment by mankoff** [comment]
On 2021-02-08 at 02:49 -08, Daan van den Heuvel <notifications@github.com> wrote...
> I'm thinking of something like this:
> `<user.navigation_option> <user.direction> <user.cursor_location> <user.navigation_input> [<number>]:
> 	user.navigation(navigation_option, direction, cursor_location, navigation_input, number or  1)`
> Example usage: 
> `go left before comma`

What about specifying direction from point somewhere in there? Forward/backward or previous/next or up/down or...

**Comment by daanvdh** [comment]
@knausj85 coding wise I really need a single entry point. The code currently Accepts any regex, So if I think of any new regex I only want to change to code at a single location and then get all the navigation options for free. I intend to make much more navigation options then only moving and extending, for instance selecting, deleting, Cutting, Replacing. There's an endless number of regex that can be useful, for instance "Everything between 2 parens". 

@mankoff I don't understand what you propose to add, what would be the functional meaning of forward, backwards, Previous, next if you already have left or right specified in user.direction. Up or down can be useful at some point.

**Comment by mankoff** [comment]
On re-reading the example sentence and the "abcd colon" example above, I think having 'left/right and 'before/after' probably covers the case I addressing. I guess I'd just point out that if this command operates across multiple lines, then "left/right" may not be technically correct, and "forward/backward" or some larger navigation term that includes navigating the larger document is correct. But left/right are simpler, shorter, and may still be the best term.

**Comment by daanvdh** [comment]
I rewrote the complete Python file and included many of the options I mentioned above. I'm going to remove the existing interfaces, if there is no strong argument in favor of it. I agree that the talon file completely unreadable for people that are new, but I don't see another way for me to implement it as flexible as it currently is. Let me know if this is in the direction of mergeable. 

https://github.com/daanvdh/talonTextNavigation

**Comment by knausj85** [comment]
let me think about it a bit, this is very similar in spirit to something else I had written back in the day and  moved away from after many complaints

that said, I can't seem to get these commands to work reliably with the latest version-just seems to always select things

**Comment by daanvdh** [comment]
Currently some overlap with this in generic_editor.talon:

`#select left:
#    edit.extend_left()
#select right:
#    edit.extend_right()
#select up:
#    edit.extend_line_up()
#select down:
#    edit.extend_line_down()`

Other than that I would not know where your problems come from, can you check whether or not the method is actually called. For me it behaves very consistently.

**Comment by daanvdh** [comment]
Also keep in mind that there is overlap with "select <number>" (going to a specific line number), As soon as you also accept numbers as input.

**Comment by knausj85** [comment]
all right, it appears the weird behavior is application-specific. I swear it was working in this particular application in the previous version though. I will have to dig further to see what we can do about it.

**Comment by knausj85** [comment]
What if we meet in the middle?

- Re-use existing arrow_key capture
- verbs defined in *.talon, consistent with what's in generic_editor and such.

something like...

```
# symbol navigation
go [<user.arrow_key>] before <user.any_alphanumeric_key> [<number_small>]
go [<user.arrow_key>] after <user.any_alphanumeric_key> [<number_small>]
delete [<user.arrow_key>] before <user.any_alphanumeric_key> [<number_small>]
delete [<user.arrow_key>] after <user.any_alphanumeric_key> [<number_small>]
extend [<user.arrow_key>] before <user.any_alphanumeric_key> [<number_small>]
extend [<user.arrow_key>] after <user.any_alphanumeric_key> [<number_small>]cut [<user.arrow_key>] before <user.any_alphanumeric_key> [<number_small>]
cut [<user.arrow_key>] after <user.any_alphanumeric_key> [<number_small>]
copy [<user.arrow_key>] before <user.any_alphanumeric_key> [<number_small>]
copy [<user.arrow_key>] after <user.any_alphanumeric_key> [<number_small>]
select [<user.arrow_key>] before <user.any_alphanumeric_key> [<number_small>]
select [<user.arrow_key>] after <user.any_alphanumeric_key> [<number_small>]
```

This has a few advantages:
- maybe a bit easier for newbies to learn
- explicit use of before/after disambiguates from e.g. "select <number>", which I use a lot.
- disambiguates "copy the" from the 

Disadvantages:
- more maintenance.

**Comment by daanvdh** [comment]
Currently before and after are meaningless for everything except for "go", so making them mandatory will be confusing. I also created some extra functionality covering the functionality of the different versions of "Word neck" and "Word prev", you can now, among many other commands, say "select left small".

Potentially in the future I will give meaning to "select before equals" it would then be the equivalent of "go before equals, select left normal" (the normal keyword currently holds the regex for "word neck", the name is up for improvement). Once I do that the default cannot be either before or after since they have different functionality. So currently you have 12 talon lines, but there will be 6 more when "default" is added to the "before" and "after" options, then you're also currently missing the user.text and user.search_option instead of the user.any_alphanumeric_key. Those 3 options we can potentially put togetherin a separate capture, otherwise we will end up with 3*18=56 talon lines.

But if you look at the bigger picture here, I'm trying to build a grammer for navigating to anything you can currently see (within 10 lines above or below the current cursor location). Making a lot of stuff easy to combine and extend. These commands are for me the most used commands even though they're a couple of days old. And I expect this to be the case for others as well. I cannot forsee what extensions we can include within this grammer, examples are: 
> select anything within brackets
> go to the next method call (language specific)
> go inside where you put your cursor (editor specific) 
> go to the nth method parameter
> rename a variable (editor specific) 
With adding more to this grammar the talon file will be more difficult to maintain, but also more difficult for new users to adjust. I think the real problem is not the readability, but it's the documentation. So adding documentation for this should solve that problem for new users. I think it is worth it to try and put this in a single talon line. I also use "go <number>" a lot, but gladly sacrificed it for this and replaced it with "[go] line <number>". The earlier ones from generic_editor.talon I never used sinse "shift left" is shorter anyway.

**Comment by knausj85** [comment]
To be clear, I simply hadn't written the user.text and user.search_option variants (which would still use the capture); just starting the conversation. The approach just helps disambiguate certain things.

The trouble with the capture approach is that we do create all these variants, so it's unclear where "after" and "before" are considered useful _now_: 

```
[<user.navigation_option>] [<user.direction>] <user.cursor_location> <user.symbol_key> [<number>]:
	user.navigation(navigation_option or "GO", direction or "RIGHT", cursor_location, text, number or  1)

[<user.navigation_option>] [<user.direction>] <user.cursor_location> <user.text> [<number>]:
	user.navigation(navigation_option or "GO", direction or "RIGHT", cursor_location, text, number or  1)

[<user.navigation_option>] [<user.direction>] <user.cursor_location> <user.search_option> [<number>]:
	user.navigation_regex(navigation_option or "GO", direction or "RIGHT", cursor_location, search_option, number or  1)
```

so if after/before aren't relevant everywhere yet, that's probably an argument against using the <user.cursor_location> capture. It creates a bunch of ambiguous commands that I would expect to work. For instance, "extend before air" does (mostly) what I'd expect, but "select before equals" doesn't. That's really pretty confusing. 

I understand the longer term capabilities, but at a certain point some things are probably best off implemented via a language server to leverage existing parsing.

What do other people think?

**Comment by knausj85** [comment]
The other challenge with making so many things optional, coupled with globally available: it will interfere will commands that have historically worked reliably. 

For instance, this command:

```
<user.navigation_option> [<user.direction>] <user.text> [<number>]:
	user.navigation(navigation_option, direction or "RIGHT", "AFTER", text, number or  1)
```

interferes with e.g. the `go back` command in a browser that's worked basically forever. Now, I'll get recognitions such as "go bat" which do the text navigation stuff.
 
These probably need to be fenced somehow

```
<user.navigation_option> [<user.direction>] phrase <user.text> [<number>]:
	user.navigation(navigation_option, direction or "RIGHT", "AFTER", text, number or  1)
```

**Comment by knausj85** [comment]
I had some time to debug the problem application; the issue was the switch to using
`actions.edit.selected_text()`
some editors are configured by default to copy the entire line when there is no selection, so the below doesn't necessarily work out-of-the-box. just something to be aware of/document

```
@ctx.action_class("edit")
class edit_actions:
    def selected_text() -> str:
        with clip.capture() as s:
            actions.edit.copy()
        try:
            return s.get()
        except clip.NoChange:
            return ""
```

**Comment by daanvdh** [comment]
You some points I hope I'm not missing one: 
1. Don't introduce meaningless commands (Before & After in combination with some navigation_options) 
2. Fence text and search_options variants
3. Make the command not overlap with existing commands, by using less optional captures (Proposal: make cursor location mandatory) 
4. Write the commands in full text, to improve readabillity. 
5. All text gets selected if no text is selected
My replies:
1. I agree with students introduce meaningless commands, I propose that I implemend before and after functionality for each of the navigation options. this will force that there will also be a "default" option that is not accessible directly for the user. Because the typical usage for "select" is that you only select the thing you say, nothing before or after it. 
2. TEXT: Agreed for text, adding "phrase" is fine. I was also thinking of making a formatter mandatory. but I currently don't see a formatter that doesn't do any formatting. I'm also not sure if you consider this fencing. 
2. SEARCH_OPTION: these options are already very limited, I don't think these need fencing, especially after what I propose at point 3.
3. you propose the following earlier [here](https://github.com/knausj85/knausj_talon/issues/341#issuecomment-776450336) 
`<user.navigation_option> [<user.arrow_key>] <user.cursor_location> <user.any_alphanumeric_key> [<number_small>]`
while testing I had some overlapping commands with using up and down, therefore I propose not to use arrow_key, but instead use my own <user.direction> which uses above and below. I also propose to make that mandatory instead of cursor_location. So then you would get:
`<user.navigation_option> <user.direction> [<user.cursor_location>] <user.any_alphanumeric_key> [<number_small>]`
4. as stated earlier, I think it's very readable but the documentation is missing. But if you're strong on this point we can write it out.
5. I'm not sure how you propose to create a setting for this. We could fix this bug by forcing that there is a selection, the downside is that we would then lose the mechanism to put back the old selection if nothing was found. For most of the navigation options this is not a problem, but for the "extend" option it is. Because you want to extend more, certainly not less. 
some additional points: 
6. I found that "go", overlaps with a lot. Therefore I'm currently experimenting with "move". 
Let me know where we agree or disagree, so that we can slowly start dropping open points.

**Comment by knausj85** [comment]
I appreciate your patience on this.

1. Implementing before and after for each makes sense to me.
2. There's a NOOP formatter that does nothing, but I don't quite follow your thought here re: using formatters?
3. I think this is reasonable.
4. If we switch to "move" instead of "go" by default as you suggest in 7, do you think using arrow_keys would be reasonable? I think making arrow_keys mandatory in conjunction with "move" would work well.
5. I am pretty strong on writing these out for the purposes of this depot. I am not opposed, though, to keeping the captures in the code for those that prefer otherwise. 
6. I can work on this bit.

**Comment by daanvdh** [comment]
1. Agreed, I will pick this up. 
2. Then you can say something like "Select right snake 'max size' " Which will select the first occurance to the right of 'max_size'. And the 'Noop' option can for instance be mapped to 'phrase', so we have "Select right phrase max size", looking for 'max size'. 
3. Agreed, No work needed. 
4. That probably makes sence, it's a trade of between re-using arrow keys or re-using "go". Though using the arrow keys does limit extending it to also include "next" and "last", which I also find usefull. But for now we can do "Move" and arrow keys. 
5. Clear. Then writing it out it is. I'll keep the non written allout version commented out in the PR. 
6. Ok, let me know how it goes. We can also keep this as a known bug for now to get merging going.

**Comment by daanvdh** [comment]
1. Is Done

**Comment by daanvdh** [comment]
I'm about to create a PR for this. I believe the only open point is 6. Do you still want this code to be put in generic_editor? I would still want to prevent making the file too big and would propose to put it in a separate navigation.talon file.

**Comment by knausj85** [comment]
I'm fine with it in a separate file, text_navigation as-is make sense to me
