### ISSUE TITLE
Vscode Linux app context wrong?

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#362]
See https://talonvoice.slack.com/archives/CCEE45RT7/p1613654398012400. Copying from there:

> Looks like the knausj code for matching the VS code window title is looking for "Code - OSS" in the name. Try this change:

```
diff --git a/apps/vscode/vscode.py b/apps/vscode/vscode.py
index bb992ea..547e681 100644
--- a/apps/vscode/vscode.py
+++ b/apps/vscode/vscode.py
@@ -11,7 +11,7 @@ and app.bundle: com.microsoft.VSCode
 """
 mod.apps.vscode = """
 os: linux
-and app.name: Code - OSS
+and app.name: Code
 """
 mod.apps.vscode = """
 os: windows
```

Would be good to know why we were looking for the "- OSS" bit, maybe we should allow either.

**Comment by knausj85** [comment]
the name is pretty fragile in my experience, developers like to randomly change it. I don't know if we need to add the executable for linux, similar to Windows?

**Comment by fidgetingbits** [comment]
I guess the reason it was looking for OSS is that certain distributions have multiple versions. the ones with OSS in the name are packages that are built directly from the git repository. the ones without are the official binaries provided by microsoft.

example from arch showing the title was `Code - OSS`:

```
aur/visual-studio-code-bin 1.53.2-1 (+995 19.08)
    Visual Studio Code (vscode): Editor for building and debugging modern web and cloud applications (official binary version)
community/code 1.53.2-1 (10.3 MiB 71.7 MiB) (Installed)
    The Open Source build of Visual Studio Code (vscode) editor
```

confirmed xprop gives the following for the OSS version.
```
WM_NAME(UTF8_STRING) = "Welcome - Code - OSS"
_NET_WM_NAME(UTF8_STRING) = "Welcome - Code - OSS"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "code-oss", "code-oss"
```
also just installed the official package:

```
WM_NAME(UTF8_STRING) = "Welcome - Visual Studio Code"
_NET_WM_NAME(UTF8_STRING) = "Welcome - Visual Studio Code"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "code", "Code"
```

so I think just matching code-oss and Code as the app names is correct.
