### ISSUE TITLE
re work vocabulary csv functionality

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#367]
posting from slack:
> 
if you want to make "bind list to csv" less cursed, make a utility function that loads a csv and returns it as a dict, then write this instead:
ctx = Context()
ctx.lists['user.vocabulary'] = load_wordlist_csv('vocabulary.csv')

stop using a lock and punching lists into another file

if you resource.open or resource.read to load the csv, it will just reload your current file when the resource changes, so you don't need to implement a reloader. (edited)

**Comment by knausj85** [comment]
> so I checked out what the current list loader does
> a lot of the logic is around creating the file if it doesn't exist yet
> so, that should be what the utility function does
> 1. load a dictionary from a file using resource.open()
> 2. create the file using the default if necessary
> 3. return the result
> 
> then to actually put it in a context, vocabulary.py can just do that
> 
> also unless there are multiple users of this function, it should probably just live in vocabulary.py?

**Comment by rntz** [comment]
I am using bind_list_to_csv in places other than vocabulary.py in my own config. But maybe if it were simpler I could just duplicate the code and not worry about it.

**Comment by rntz** [comment]
As long as we're rewriting this code we might as well fix #339 as well.

**Comment by rntz** [comment]
Planning on taking a shot at this on my live stream on Sunday.

**Comment by knausj85** [comment]
I've already got this locally, just need to merge.

**Comment by knausj85** [comment]
Note to self: need #356 merged first.
