### ISSUE TITLE
Key modifiers not working with numpad (keypad)

### ISSUE THREAD

**Issue by adam-edison** [knausj85/knausj_talon#368]
When defining a keypress string in a talon file, if there are any modifiers, the keys are not pressed correctly.

- `key(cmd-ctrl-alt-keypad_2)` results in nothing happening
- `key(ctrl-alt-keypad_2)` results in the `2` key being pressed
- `key(keypad_2)` results in the `2` key being pressed

This was only tested on mac.

**Comment by knausj85** [comment]
@adam-edison 
this looks like a Talon-bug, you should report that one here:
https://github.com/talonvoice/talon/issues

**Comment by adam-edison** [comment]
Will do, thanks!
