### ISSUE TITLE
Evaluate some functionality from mr-talon

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#387]
specifically https://github.com/mrob95/MR-talon/commit/9a5f4af5681be7d19f474c2f4ff9e609f7fddcec for dictating talon files and talon-specific Python stuff 

 I was working on something similar, but this is more baked

**Comment by pokey** [comment]
Wow that's pretty cool! Only thing a bit hacked is the hard-coded list of spoken forms, but I'm not sure we have a better solution floating around do we?

**Comment by pokey** [comment]
I wonder if it's worth trying to create a global `make_speakable` that includes things like numbers, reads from a csv, etc

**Comment by knausj85** [comment]
Yeah, ideally, there should be global actions for create_spoken_form(s) that's floating around in various places.

**Comment by fidgetingbits** [comment]
I'm just adding a reference to this https://github.com/rexroni/rexroni_talon/blob/master/speakify.py, although I haven't used his stuff yet, I was going to try to give it a whirl when I added some of my older management stuff soon

**Comment by pokey** [comment]
that looks awesome!  i think we could prob just use that out of the box for at least a couple different places, eg application names
