### ISSUE TITLE
create_spoken_form refactor

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#399]
This has been peppered in a few places. This should be an action with any necessary context-specific overrides.

- [ ] Action implementation
- [ ] Context-specific replacement list or something? Need to think about it.
- [ ] Number support for w2l. Maybe just serial digits to start.
- [ ] Continue letting Dragon parse numbers
- [ ] Use in switcher.py for all platforms? I used this initially for Windows only to avoid irritating other users.

**Comment by pokey** [comment]
For sure. Would be cool if it supported numbers too

**Comment by knausj85** [comment]
Yeah, I was thinking numbers should be supported via speaking digits serially at the very least. 

Dragon parses the numbers for us, so that functionality should be preserved when its active.

**Comment by knausj85** [comment]
note to self: https://github.com/rexroni/rexroni_talon/blob/master/speakify.py

**Comment by knausj85** [comment]
Closing in favor of #413

**Comment by pokey** [comment]
oh wow super weird.  I was sure there was an issue like this but for some reason I could not get it to come up in github search so I created a new one
