### ISSUE TITLE
open csvs in utf8 mode

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#401]
e.g. open(path, 'r', encoding='utf8')

Slack link: https://talonvoice.slack.com/archives/C7ENXA7C4/p1616876829071900?thread_ts=1616876356.067400&channel=C7ENXA7C4&message_ts=1616876829.071900

Seems like this broke someone's additional_words.csv

**Comment by knausj85** [comment]
I believe this is most likely a talon bug, as I was under the impression it
forced utf8. I’ve tested around this on Mac and Windows

resource.open also doesn’t have an encoding parameter IIRC

**Comment by rntz** [comment]
Yes, there seems to be further debugging happening in this slack thread. Closing this for now.
