### ISSUE TITLE
Switching between windows doesn't work

### ISSUE THREAD

**Issue by katarkor** [knausj85/knausj_talon#410]
Hi, 
I'm completely new to Talon and I'm just trying to figure out how things work. I'm currently stuck at switching between windows: if I understood it correctly I'm supposed to use "focus" and "running list" to do that, but the "focus" command doesn't do anything and the running list is empty. Am I doing something wrong or is it a bug? I'm using Talon 0.1.4 and macOS Catalina 10.15.7, I downloaded all the files in this repo 28.03.

**Comment by knausj85** [comment]
The current version of the repository requires Talon v0.1.5. Can you update and try again?

If the issue persists, can you attach your talon.log?

**Comment by splondike** [comment]
Issue is a help request, and there hasn't been a reply in a while so I'm going to close this.
