### ISSUE TITLE
give all windows that can be openable with voice commands a visible way to close

### ISSUE THREAD

**Issue by timo** [knausj85/knausj_talon#416]
the full help menu has the close button at the bottom, but ~alphabet and~ formatters don't (i think)

since it's so easy, they could also be clickable

also, can we figure out if the help menu is too large for the screen so that the bottom gets cut off? that's a way to not be able to use it, if you can't see the bottom.

**Comment by splondike** [comment]
#588 has addressed the first bit, I've made #619 for the second part. Closing out this issue.
