### ISSUE TITLE
text navigation works in all text editors but not in visual studio

### ISSUE THREAD

**Issue by akaflokart** [knausj85/knausj_talon#434]
hi,

the text navigation works in notepad and notepad++ but not in VS (2017/2019).
It selects the 10 words but nothing else.
Any idea why this happend.

Thanks in advanced

**Comment by knausj85** [comment]
This is usually due to a setting like "copy copies entire line if nothing is selected." Is that something that's enabled in VS?

**Comment by akaflokart** [comment]
It seams there is no option to disable "copy copies entire line if nothing is selected".
Only " copy empty line without selection " can be disabled.
![Capture](https://user-images.githubusercontent.com/41044719/119242957-c585c700-bb62-11eb-8c5e-7bfdc5a72ccb.PNG)

Unbelievable.
Thanks for your help

**Comment by akaflokart** [comment]
I used this [addon](https://marketplace.visualstudio.com/items?itemName=KiwiProductions.CopyOnlySelection) to bind ctrl+c to only selected text.
Now it works.
