### ISSUE TITLE
Non-speakable characters in lists

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#440]
Noticed this warning:
```
2021-05-28 20:48:36 WARNING Skipped unknown tokens: [',', '-', '1', '3', '`']
```

These tokens are not handled by wav2letter when included in voice commands.
After some hunting it appears to be because of the following lists:

```python
>>> set([n for n,ls in registry.lists.items() for s in ls[0] for c in "13,-`" if c in s])
{'user.symbol_key', 'user.punctuation', 'user.running', 'user.help_contexts'}
```

For `symbol_key` and `punctuation` we could probably use some context sensitivity to not bind these symbols (comma and back tick) unless we're using dragon. For the list of runing applications and help context, we could either filter out things that aren't speakable or try to create our own spoken forms.

Aegis also suggested some other possibilities on slack:

> you can also petition me to do one of these:
> - add an api that lets you transform words for a language
> - ship my own model / code that transforms words for a language

**Comment by pokey** [comment]
Re spoken forms, just wanted to cross-ref #413 and https://github.com/pokey/pokey_talon/commit/30b58d26ae60d9610208864e3cc591361401e6e1
