### ISSUE TITLE
[IntelliJ/Jetbrains] 'Select line' doesn't do anything

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#450]
The generic text command 'select line' does not work within IntelliJ

Expected behavior: "select line" highlights the entire line with the cursor
Current behavior: "select line" does not seem to have any effect

**Comment by splondike** [comment]
Do the other IntelliJ RPC things (in apps/jetbrains/jetbrains.talon) work for you? E.g. does `refactor rename` work? If not, have you installed this plugin: https://github.com/knausj85/knausj_talon#jetbrains-commands ?

**Comment by xavier630** [comment]
I haven't installed the custom Jetbrains plugin, but to be honest, I would expect commands from `text/generic_editor.talon` to work in any text editor/text input without additional custom plugins (and where the keybindings are abnormal for a given app, they are mapped manually for that map in a .talon file for that app such that the commands still work).

Are there some limitations that mean we can't strive for this? Sorry, I'm pretty new to Talon so unaware of the various limitations and hoping for an ideal state where everything works out of the box :P

**Comment by knausj85** [comment]
jetbrains.talon/jetbrains.py currently overrides a bunch of the actions
used by generic_editor.talon in fashion which requires the plugin:

https://github.com/knausj85/knausj_talon/blob/f6daebc40eabe39e4804f14a6b17f30563e97cc2/apps/jetbrains/jetbrains.talon#L32


There has been some discussion to fallback to an implementation that
doesn’t require the plug-in, but no such work has been done for jetbrains.

For now, you’re probably better off trying the plug-in. You could also
remove the jetbrains-specific files for now, but you’ll lose a lot of good
functionality.

**Comment by xavier630** [comment]
Thanks, that makes sense 👍
