### ISSUE TITLE
[FR] Commands to apply format options to selected text

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#452]
Currently one can say "quote that" to add quotes to selected text.

I propose commands like 'snake that' to apply formatting to selected text (there could be one command per formatter).

**Comment by splondike** [comment]
We've got this one already, try out 'title smash that' for example. The code in question is misc/formatters.talon:8

**Comment by xavier630** [comment]
Ah, my bad, I tried it earlier, but you're totally right, it's working for me.

Cheers @splondike
