### ISSUE TITLE
[FR] Command to unfocus text

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#453]
Some commands like escape and tab sometimes work, but not in all cases.

This feature would be useful in places like a browser + vimium setup where by unfocusing, you can then say 'fine' to show links rather than inserting an 'f' into the text field

**Comment by awulkan** [comment]
Where doesn't it work? Also, do you have any suggestion for how to make it work?

**Comment by xavier630** [comment]
Some places where escape doesn't work:
* The browser address bar
* IntelliJ
* Slack

Tab is pretty decent but suffers from many similar issues and you risk selecting other elements which can have unforeseen expects when trying to run commands but really just entering text into them

I don't have a potential solution but I wanted to raise the issue.

Cheers,
Xavier

**Comment by splondike** [comment]
I'm not sure how you could make this work reliably in all contexts. Maybe we should just look at your specific suggested use case of Vimium? Maybe you just want to map a new command that presses escape and then the letter f? That might close popups or the like though.

Even for your specific case I'm not sure we can have a reliable solution without integration with the browser, or the ability to bind a specific key (e.g. F13) to swap to normal mode in Vimium.

**Comment by xavier630** [comment]
Going to close since it seems like there's not a great solution for all cases and escape covers 80% of cases
