### ISSUE TITLE
[Bug - Chrome] Tab close {nth} closes only one tab

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#454]
Likely because some sort of sleep needs to be built in to the ordinal form of the tab close command (or a different chrome shortcut needs to be used to select multiple tabs before pressing cmd-w)

Occurring in Chrome 91.0.4472.77 for me.

**Comment by splondike** [comment]
Hmm, "tab close third" works for me on Linux in both Chrome 90.0.4430 and Firefox 88.01. Does the "DECODED" line in Talon show it as having recognised the command in its entirety?

**Comment by xavier630** [comment]
Yep, it shows as understanding the command and closes up to two tabs, but it doesn't seem to close more than two tabs for me.

Mac OS 10.15.7

![image](https://user-images.githubusercontent.com/9077250/120810745-5cd41c80-c55c-11eb-9336-a247ea0946d9.png)

**Comment by lunixbochs** [comment]
Try putting a sleep in your close tab action, after the key is pressed. The problem with sleeps is they vary person to person based on stuff like machine speed and load.

**Comment by xavier630** [comment]
In terms of concrete actions, is it worth putting a sleep into the default library so that this works for every one out of the box?

**Comment by lunixbochs** [comment]
> putting a very small sleep into the default library

What I mean is it's hard to tune such a sleep to actually work for everyone, so you typically need to overshoot the sleep time if you do that.

**Comment by splondike** [comment]
I think it would be fine for you to experiment with how long of a sleep you need to make it behave the way you expect. You can override the tab close action inside the `apps/chrome/chrome.mac.talon` file in your pull request. If the sleep time is < 250ms say I don't think it'd be an issue.

I realize we have some pending pieces of work to migrate all the action implementations from .talon to .py files using the migrator that lunixbochs has made, as well as stop using dots in filenames. I think we'll do those as a single big commit though so anything you do here will be rolled up into that later on.

**Comment by xavier630** [comment]
It could make more sense to make it repeat delays (if we wanted to implement them in a generic way) a possible annotation on actions so that you can take advantage of app/os contexts
