### ISSUE TITLE
[FR] Functionality to play sound on sleep/wake

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#455]
Like here: https://github.com/jcaw/talon_config/blob/master/utils/sound.py

This could be a configuration setting since likely isn't desirable for everyone

**Comment by lunixbochs** [comment]
I will recommend against having this in knausj directly due to the estimated stability of the underlying code. You should modify your wake up talon script locally

**Comment by xavier630** [comment]
I mostly put it here because I thought others would benefit, but that makes sense. Will close.
