### ISSUE TITLE
Interest in integrating some pandas snippets?

### ISSUE THREAD

**Issue by nickeubank** [knausj85/knausj_talon#468]
Wrote a handful for pandas data science work -- should I make PR to integrate? 

```talon 
# Common Pandas Needs

group by: 
    insert('.groupby([""])')
    edit.left()
    edit.left()
    edit.left()

describe: ".describe()"
columns: ".columns"
some: ".sum()"
as type:
    insert('.astype("")')
    edit.left()
    edit.left()

value counts: ".value_counts()"
value counts missing: ".value_counts(dropna=False)"
value counts normalized: ".value_counts(normalize=True)"
value counts normalized missing: ".value_counts(normalize=True, dropna=False)"
value counts missing normalized: ".value_counts(dropna=False, normalize=True)"

# Getting columns. 
# Column was too close to colon, and "col"/"call" 
# wasn't reliable. So... cake!
cake:
    insert('[""]')
    edit.left()
    edit.left()

cake named <user.text>:
    insert('["{user.text}"]')

cake list:
    insert('[[""]]')  
    edit.left()
    edit.left()
    edit.left()    

# Indexing
lock: 
    insert(".loc[]")
    edit.left()

eye lock: 
    insert(".iloc[]")
    edit.left()

```

**Comment by splondike** [comment]
My feeling is we would leave this out. One thing to consider with all these commands is whether other people will find them or if they will just go ahead and build their own version. 

In my opinion the knausj repository ideally would define a small-ish set of voice commands that would be applicable across a wide variety of applications and settings and would let you use the functionality of your computer in a basic way. Very specific things, particularly when they're programming stuff might be better left for other packages which could be installed in addition to knausj. I think aegis plans to make installing packages easier in the medium term (with a GUI), so this would fit well with that.

Let me know what you think, I might just have a different view of this to other Talon users.

**Comment by ym-han** [comment]
I personally agree with splondike for the following reasons:  

* Assuming things are made modular, it's easier to add on packages / additional functionality than to remove the stuff (without breaking things), and it's easier for new users to figure out how things work by building up than by taking things apart
* the more commands in one's grammar, the higher the risk of getting accidental or non-intended output
