### ISSUE TITLE
How to get interactive window recognized as Python in vscode?

### ISSUE THREAD

**Issue by nickeubank** [knausj85/knausj_talon#480]
I work a lot in the Jupyter interactive window in python, but it's little terminal input isn't recognized as being "python". How does one tweak that?

The window when jupyter console is active looks like this:

![image](https://user-images.githubusercontent.com/9683693/124025223-315b1b00-d9be-11eb-8db8-de4841153826.png)

I tried adding `Interactive - #1` to the language suffix list (e.g. "Interactive - #1": "Python"), but didn't seem to work.

**Comment by knausj85** [comment]
You could do something like this in python.talon. I'm 100% unfamiliar with jupyter. 

```
mode: user.python
mode: command
and code.language: python
mode: command
and app: vscode
and title: \Interactive\
```

The other alternative would be to use the force commands in language_modes.talon.

**Comment by lunixbochs** [comment]
aren't regex slashes the other /way/

**Comment by nickeubank** [comment]
Perfect, thanks!

The interactive console in vscode, especially in this configuration, is definitely an edge case. Normally jupyter indicated by￼ .ipynb.
