### ISSUE TITLE
Add screenshot commands to capture a particular screen

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#491]
e.g.,
```
^grab screen <number_small>$:      user.screenshot(number_small)
^grab screen clip <number_small>$ : user.screenshot_clipboard(number_small)
```

**Comment by AndreasArvidsson** [comment]
I've already have this on my todo but I was waiting for aegis implementation of a properly sorted screen ordering. For now we could probably just use the same as the switcher though.

**Comment by knausj85** [comment]
The other interim alternative would be to make it a two-step process and
display an index on each via a canvas, if the ordering is problematic

**Comment by AndreasArvidsson** [comment]
A two step process sounds a little annoying. If you only have two screen remembering which one is which is easy and now the flash confirms it, but I could make a voice command to show a number on each screen as a separat feature. I still think the screen capture and switcher should have the same ordering.
