### ISSUE TITLE
Command 'phones that' doesn't respect existing case

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#501]
For example if we're looking at homophones for the word `Sea` and we pick `see`, it will be added in entirely lower case which isn't ideal since usually the existing case is there for a reason, eg it's the first word in a sentence.

This is only the case when picking a word from the GUI.

One potential solution would be to look at the existing word and see which Talon formatter matches what has been used (possibly by applying them one-by-one to the selected word and looking for equality with the selected word), pick a default if no formatters match, and then apply that formatter to all of the options from the homophones list.

**Comment by knausj85** [comment]
in the interim, there is a command to select and format the homophone

```
choose <user.formatters> <number_small>:
    result = user.homophones_select(number_small)
    insert(user.formatted_text(result, formatters))
    user.homophones_hide()
```

**Comment by splondike** [comment]
xavier has fixed this. Closing issue.
