### ISSUE TITLE
"Phones that" suggestion

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#519]
**Suggestion**
As a quality-of-life improvement, the command `phones that` could select the word that the cursor is currently on (only when no text is already selected). 

**Reasoning**
This is because the `phones that` command almost always requires the user to manually select a word and it would be much more efficient if it automatically selected a word for the user. This would mean that the usual homophone workflow would require one fewer command.

If we wanted to take it further we could do this for all of the `{x} that` commands but I think homophones are a good place to start because they often (always?) apply to just one word.

**Proposed implementation (if any)**
This would be quite easy to implement as it would just require the select word function at the start of `phones that`.

**Comment by xavier630** [comment]
On reflection, I think it's better to leave `phones that` as is and add a new `phones word` following the pattern started [here](https://github.com/knausj85/knausj_talon/pull/531). That keeps each command as modular as possible rather than introducing additional responsibilities and complexity to specific commands and making `phones that` out of line with other `x that` commands.

**Comment by rntz** [comment]
Good idea, I've added a "phones word" command to #531.
