### ISSUE TITLE
Select word edge case on Windows, Linux

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#526]
I did some rough investigation and, from the code, I suspect that the edge case I encountered in https://github.com/knausj85/knausj_talon/issues/499 is also present on Windows and Linux.

Linux:
![image](https://user-images.githubusercontent.com/9077250/127769371-4664836c-9c9f-47cd-b41a-98f607aeb9e7.png)

Windows:
![image](https://user-images.githubusercontent.com/9077250/127769378-f4118222-dd16-4051-b5ff-ee152eea73ff.png)

**Comment by splondike** [comment]
The above PR addresses this, closing.
