### ISSUE TITLE
Default python implementation for generic_browser

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#532]
This probably applies to other `generic x` classes of commands as well but I noticed looking at generic browser that there is a lot duplication of implementations across browsers due to not having any default implementations to inherit from.

The command -> action mapping only needs to be registered once at the generic browser level which is probably where a default implementation should be too in order to avoid this duplication:

**Example**
The `go(url)` command is implemented identically four times (once for each browser):
![image](https://user-images.githubusercontent.com/9077250/127818355-99a953d6-0f70-424a-b9e9-b5df3cfd1d16.png)

**Comment by splondike** [comment]
#1117 has reduced duplication and put together some default browser actions. Closing this out.
