### ISSUE TITLE
Tab last/next in Mac terminals should switch tabs

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#551]
`tab next` and `tab last` don't do anything in the Mac terminal.

For a quick look at the code, it looks like the tag is implemented, so I suspect it just needs some custom keybindings.
https://github.com/knausj85/knausj_talon/blob/master/apps/platforms/mac/terminal/terminal.talon#L8

Latest knausj master, August 2nd 2021
Talon 0.2.0-8
Terminal version 2.10 (433)

**Comment by ViacheslavKudinov** [comment]
As I understood it comes from https://github.com/knausj85/knausj_talon/blob/12c2e6830a74a7e5cff6138969368642a0a567a6/code/platforms/mac/app.py#L15 and https://github.com/knausj85/knausj_talon/blob/12c2e6830a74a7e5cff6138969368642a0a567a6/code/platforms/mac/app.py#L19, but according to official doc it is different shortcuts for standard Mac terminal https://support.apple.com/guide/terminal/keyboard-shortcuts-trmlshtcts/2.11/mac/11.0

**Comment by xavier630** [comment]
Yeah it's ctrl-tab when I do it manually like the Mac doc you found says 👍

Should be an easy-ish fix to overwrite those two commands in the terminal context for Mac.

**Comment by ViacheslavKudinov** [comment]
@xavier630 I found there some discussion about refactoring of terminal in general https://github.com/knausj85/knausj_talon/issues/505
Maybe it makes sense to follow that issue as tabs implementation also was mentioned there.

**Comment by ViacheslavKudinov** [comment]
As I understood it can be implemented as a part of #514.
At least according to the new "generic style".

**Comment by DonnerWolfBach** [comment]
PR #514 will only implemented kde-konsole according to the new "style". For tracking which terminals are in knausj but not yet migrated to the new style, #562 was created. 
[This branch](https://github.com/DonnerWolfBach/knausj_talon/tree/knausj_generic_terminal_macos) contains an implementation in the new style for the apple terminal, however **it is not tested** since I do not have a mac.

**Comment by DonnerWolfBach** [comment]
Thanks to @xavier630, who tested my [apple_terminal implementation](https://github.com/DonnerWolfBach/knausj_talon/tree/knausj_generic_terminal_macos), I was able to implement "tab next" and "tab (last|previous)" the right way. I will open a (drafted) PR where you can comment/add changes you want to have.

**Comment by bookcasey** [comment]
I feel this issue is best resolved by changing the generic tab shortcut. It's not an issue unique to the Terminal. I submitted a PR that resolves it in Terminal, in addition to identical issues in Finder and Safari 😄
