### ISSUE TITLE
Homophones GUI should hide/deprioritise current word

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#552]
**Issue**
The list of homophones options shows the word that the user is already looking at somewhere in the list (see the screen shot at the bottom).

This doesn't make much sense since a user wouldn't request homophones of a word if they are happy with the word as it is.

**Reasoning**
This has some minor negative effects like increasing cognitive load and decision-making time.

**Potential Solutions**
I think it's pretty safe to either not show the word, or, if we find a good reason to keep showing it, then to always display it last since it's least likely to be the word that a user is looking for.

![image](https://user-images.githubusercontent.com/9077250/128165145-214503b5-788e-499e-bdbf-fc90f7863a86.png)

**Comment by splondike** [comment]
Fix for this has been merged #596 . Closing.
