### ISSUE TITLE
`over` not working with `ship` command

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#567]
I can no longer trigger the end of a `ship` command with over. This used to work fine for me but not right now. I'm on the latest knausj develop.

Talon now understands `over` as `one` which I believe is because `over` is no longer an option for for the `ship` command.

I would love for someone else to validate that this also happens to them.

**Comment by rntz** [comment]
AFAICT, `over` should never have worked with `ship`? To terminate `ship` you can use either `sunk` or `lowercase`.

https://github.com/knausj85/knausj_talon/blob/0414eddd348a0314101978c4ed7eaf3cbfc00373/misc/keys.talon
