### ISSUE TITLE
Full screenshot functionality for Mac

### ISSUE THREAD

**Issue by 2shea** [knausj85/knausj_talon#59]
The following three screenshot voice commands only work for windows:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/3289426/78613737-6b705800-7821-11ea-94b3-fcfd45530f76.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/3289426/78613660-45e34e80-7821-11ea-9b4e-79a4ae2171e7.png">

It would be great to have these commands work for Mac as well.

**Comment by knausj85** [comment]
Fixed

https://github.com/knausj85/knausj_talon/commit/baa323fcd34d8a1124658a425abe8eed59cf2ee5
