### ISSUE TITLE
window_move_desktop <number> fix

### ISSUE THREAD

**Issue by ghost** [knausj85/knausj_talon#591]
The following command to move a window to a different mac desktop in desktops.py stopped working:
window_move_desktop <number>: user.window_move_desktop(number)

Aegis offered the quick fix below. Apologies I'm not submitting a PR because I break things when try to do that.

The above command works after lines 36-38 of desktops.py are changed to
    rect = fs.AXFrame
    x = rect.x + rect.width + 5
    y = rect.y + rect.height / 2

**Comment by rntz** [comment]
Should be fixed if/when we merge #1054
