### ISSUE TITLE
user.switcher_focus("gnome-terminal") fails since spoken forms introduction

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#599]
Since #470, running `user.switcher_focus("gnome-terminal")` fails even though `gnome-terminal` is running. This breaks some of my commands, which call `user.switcher_focus` directly with application names:

```
talon.scripting.talon_script.TalonScriptError: 
 in script at /home/rntz/.talon/user/mine/custom.talon:9:
 > user.switcher_focus('gnome-terminal')
RuntimeError: App not running: "gnome-terminal"
```

I suspect this is because somehow spoken forms are being used where IMO they shouldn't -- `user.switcher_focus` shouldn't take a spoken form, it should take the name of the application, and the `{user.running}` list should map spoken forms to proper application names. @pokey is this accurate? I may have some time in the next two days or so (depending on internet access) to pair on this.

**Comment by pokey** [comment]
Looking at the code, it appears `switcher_focus` still uses app name, not spoken form, so not sure what's causing this issue for you

**Comment by splondike** [comment]
"focus gnome terminal" is working for me on 2a3b59f8d194ee141fa6d595b1ce294d096a2c9c with i3 and Fedora.

**Comment by rntz** [comment]
it works if I use `Gnome-terminal` instead of `gnome-terminal`.
