### ISSUE TITLE
"Help Context Generic Browser" Command

### ISSUE THREAD

**Issue by tararoys** [knausj85/knausj_talon#60]
I speak the command 

"Help Context Generic Browser" 

Problem: It is supposed to open the generic browser help context menu.  It does it about one time in four.  Have to repeat the command 3 times with the right accent, and then it opens  the generic browser help context menu.  Still not sure what the right accent/pronunciation is.  It seems to have trouble with the word 'generic' since after that word it prints the word 'browser' in a text field if I have a cursor in a text field while giving that command.  

Not sure if training the system more will help.  This issue cropped up the first day I was using it.  

OS: windows 10

documentation on the full QA test of the help context generic browser command set can be found here:  https://gist.github.com/tararoys/041cf944f2d275176ea56eb2d24f5493

**Comment by knausj85** [comment]
This is the sort of situation where you may need to override the words/commands used so they are recognized better for you. Dragon training sometimes helps, sometimes doesn't.

I've added the ability to override the display name + what's used to bring it up in this check-in:
https://github.com/knausj85/knausj_talon/commit/1389c48c5583acae771eb571f1fb144d41ce48d0#diff-5c8283e519c859627e6fda41fa995cc6

Also, commands were added (and some tweaked) to make help entirely navigable by voice. When in the "help all" or "help active" menus,  the context is selectable by the displayed number now too. e.g. help 1, help 2, which may also help in this sort of scenario.
https://github.com/knausj85/knausj_talon/commit/1a67060a38523e42193f8edd4cf3dffc15b39673
