### ISSUE TITLE
DFA compilation performance problems due to large talon lists since #506

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#600]
Since #506 DFA compile times have gone way up for me. In most contexts they went up about 10ms, which is tolerable; but while editing .talon files in Emacs they increased about 500ms! I believe both effects are due to large lists auto-generated from the talon registry (actions, lists, settings, etc.), declared and loaded in lang/talon/talon.py: https://github.com/knausj85/knausj_talon/blob/04303fbf5390a9aa59a1ed1d7e21676406948561/lang/talon/talon.py#L7

The 10ms universal increase I believe is due to talon_helpers.talon, eg: https://github.com/knausj85/knausj_talon/blob/04303fbf5390a9aa59a1ed1d7e21676406948561/misc/talon_helpers.talon#L36

The talon-language-specific increase is due to lang/talon/talon.talon, eg: https://github.com/knausj85/knausj_talon/blob/04303fbf5390a9aa59a1ed1d7e21676406948561/lang/talon/talon.talon#L49

I'm not sure what the right approach to take here is. In future improvements to talon itself will hopefully make large lists like this a non-issue. But a .5s DFA compile time increase is pretty awful. As I see it our options are:

1. Do nothing and wait for talon to improve. I'll probably disable these commands locally. Hopefully this doesn't affect many people, my CPU seems to be particularly bad at DFA compilation.

2. Remove these commands entirely. This is a shame, since these seem hella useful for writing talonscript.

3. Find the most problematic lists (I suspect user.talon_actions but haven't tested) and fix them somehow. Possibly the best approach is to switch to a bag-of-words approach: generate a list of all words used in talon action spoken forms, call it `{talon_action_words}`, and where we currently use `{user.talon_actions}` instead effectively use `{user.talon_action_words}+`; assuming there are fewer words than action names, this should improve compile times at the cost of a little fuzziness.

**Comment by pokey** [comment]
Bag of words is an interesting idea here. I'd be inclined to do that or to just comment out the problematic ones with a note saying people can turn them on if they want them. I have them commented out in my repo

**Comment by rntz** [comment]
Dump of the sizes of the lists of talon things for me:
```
user.talon_scopes: 10
user.talon_apps: 41
user.talon_tags: 58
user.talon_modes: 77
user.talon_captures: 114
user.talon_settings: 114
user.talon_lists: 130
user.talon_actions: 1418
```

So `talon_actions` is clearly the largest; the rest together are about 40% its size.

**Comment by pokey** [comment]
Mind dropping your dump snippet here? Would like to quickly pull with cursorless active

**Comment by knausj85** [comment]
needless to say, these commands are exceptionally handy in my experience.

I'm not opposed to option number three, or potentially disabling by default for now

**Comment by lunixbochs** [comment]
The first issue I'm talking about is that the lists are globally populated regardless of whether you're using them for anything. This causes an issue for dragon in all contexts, rather than just contexts where those lists would be used. You can mitigate it by only populating those lists in a context where commands are using them.

As for create spoken forms on file manager, ~10,000 entries is still quite a lot for conformer. Do you actually need that many ways to say each word?

**Comment by wolfmanstout** [comment]
To clarify, these lists are currently used in a global grammar: https://github.com/knausj85/knausj_talon/blob/04303fbf5390a9aa59a1ed1d7e21676406948561/misc/talon_helpers.talon#L36

For me, the latency hit is not worth putting in a global grammar. I would be fine with opt in or a tighter scope.

**Comment by knausj85** [comment]
@lunixbochs 
For reference, what's a "reasonable" limit for list size with Conformer? 
The `create_spoken_form` currently generates subsequences for file/folder names which is very convenient for small number of folders & files. It's definitely not great idea for folders approaching the current cap of 1000 files or folders.  For some number of items, I think it makes sense just to disable this behavior.

**Comment by nriley** [comment]
Making talon_* lists opt-in broke the limited support that knausj had prior to this (for which a list is still declared: https://github.com/knausj85/knausj_talon/blob/master/lang/talon/talon.py#L35). We had agreed at the knausj grooming session this morning to restore this functionality for those of us who cannot afford the latency hit. Fix incoming…

**Comment by rntz** [comment]
Gonna close this, it seems like we've solved the problem. Would be nice to re-enable these by default on w2l but we can't enable them by default globally because of Dragon.
