### ISSUE TITLE
Tobii 5 - Talon Eye Tracking menu is greyed out

### ISSUE THREAD

**Issue by slimlime** [knausj85/knausj_talon#602]
I believe the wiki steps referred to the same models https://talon.wiki/tobii_5/ here intended to automatically make eye tracking available

![image](https://user-images.githubusercontent.com/30815731/133943304-9cd5f189-d433-4dad-b2bf-684f773d0120.png)

Not sure about dev/debug steps to see more on either the Talon or Tobii software side.

---
On Windows

**Comment by AndreasArvidsson** [comment]
On windows you have disable the tobii services as they take complete control of the hardware blocking talon from using it.

**Comment by splondike** [comment]
Looks like this has been addressed, closing the issue.
