### ISSUE TITLE
"Go Forward" command in Generic Browser

### ISSUE THREAD

**Issue by tararoys** [knausj85/knausj_talon#61]
I speak the command: 

"Go forward"

while in the firefox browser 

	problem: the command works exactly like "forward," which is fine.   The issue is a documentation issue:  "Go forward"  is not listed on the  help context generic browser command list help page.

documentation on the full QA test of the help context generic browser command set can be found here:  https://gist.github.com/tararoys/041cf944f2d275176ea56eb2d24f5493

**Comment by knausj85** [comment]
I believe this is very likely a command built into dragon, so there's nothing I can do here. Per https://www.nuance.com/products/help/dragon/dragon-for-pc/enx/professionalgroup/main/Content/Web/web_basics.htm

Does anything show up in the command history window ('show command history') when you use 'go forward' command? That'll give you some indication whether it's these scripts, or dragon itself.

**Comment by tararoys** [comment]
when I said "show command history,"  the only thing that showed up in it was the "forward" command.

None of the following appear in the command history: 

"Go forward"
"Go back"
"Go Backward"

All of the commands work as expected to go forward and backward in the browser window history.

**Comment by knausj85** [comment]
this is a result of a Talon bug -

https://github.com/talonvoice/beta/issues/34

so I’m going to close this for now.

I also think it depends on the browser, as I see go back in history when I use chrome.
