### ISSUE TITLE
"bookmark show" command in help context generic browser

### ISSUE THREAD

**Issue by tararoys** [knausj85/knausj_talon#62]
While in firefox, on my windows 10 machine, I said: 

"bookmark show"

as expected, this shows me my bookmarks.  

Problem #1 : help context generic browser does not explicitly say the "close window" command will close the bookmark window, although it seems like a fairly intuitive assumption.  I certainly figured it out.  This apparently created problem #2: 

Problem #2: while looking to see if a folder was actually created, I used the "bookmark show" command. This opened a file browsing window showing my bookmarks.  I switched to notepad with the "focus notepad" command, which brought notepad forward. Then I said "focus firefox," which only brought the firefox bookmark window forward. Then  I use the "window close" command to close the bookmark window. My Firefox window was still behind my notepad window after this. Saying "focus Firefox" did not bring Firefox back in front of notepad.  ( I assume that even though I had closed the bookmark window, that was still considered a firefox window.  So the focus was on firefox still.  If I had to guess.)  I had to say "focus notepad" and then "focus firefox" to enable to main firefox window to be brought all the way forward to where I could see it.  

documentation on the full QA test of the help context generic browser command set can be found here:  https://gist.github.com/tararoys/041cf944f2d275176ea56eb2d24f5493

**Comment by knausj85** [comment]
Problem #1: "close window" is a globally available command for any application. This is defined here
https://github.com/knausj85/knausj_talon/blob/master/misc/window_management.talon. 

To get a better feel for everything that's active, try the "help active" command (just changed tonight), or "help active context" for older versions. This will update as the active application/window changes.

Problem #2 is actually consistent with Window's alt-tab key behaviour. It brings forward whatever the last active window was for the application. I recommend installing https://neosmart.net/EasySwitch/ so you can then use "next window" and "previous window" to then cycle thru the windows after saying "focus firefox"

**Comment by knausj85** [comment]
I think we can close this one since it's consistent with standard Windows behavior.
