### ISSUE TITLE
"Bookmark bar" command in help context generic browser

### ISSUE THREAD

**Issue by tararoys** [knausj85/knausj_talon#63]
In firefox, on my windows 10 machine, I said the command 

"Bookmark bar"

	problem: this command does not seem to do anything. Nothing appears on the screen when it is spoken into the microphone and the focus is on Firefox the browser.

documentation on the full QA test of the help context generic browser command set can be found here:  https://gist.github.com/tararoys/041cf944f2d275176ea56eb2d24f5493

**Comment by knausj85** [comment]
Out of the box, firefox has no shortcut key to show the bookmark bar. I'm kinda leaning towards keeping this depot respectful of the defaults for folks.

I believe it is possible to create a custom one for yourself locally, if you want this functionality. The browser.bookmarks_bar would just need to uncomment and updated to match the shortcut you choose.
https://github.com/knausj85/knausj_talon/blob/master/apps/win/firefox.talon
