### ISSUE TITLE
"show cache" command in help context generic browser

### ISSUE THREAD

**Issue by tararoys** [knausj85/knausj_talon#64]
On my windows 10 machine, in firefox, I said

"show cache"

The first time I said it, a window appeared with a bunch of checkboxes and such. This was after I had been testing nearly every other command in the generic browser help context, so I had done a lot of browsing.  

I shut down firefox, restarted my computer, restarted firefox, and said "show cache."  No window appeared and nothing happened.   I repeated the command several times.  I expected a window to appear like the first time, but no window ever did.  

documentation on the full QA test of the help context generic browser command set can be found here:  https://gist.github.com/tararoys/041cf944f2d275176ea56eb2d24f5493

**Comment by knausj85** [comment]
Does this issue occur if you switch from firefox to something else, then back? 

I think it might be a bug in Talon
