### ISSUE TITLE
Fine grain support for programming language features

### ISSUE THREAD

**Issue by wenkokke** [knausj85/knausj_talon#651]
I would like to refractor code.py and the generic tag into several smaller files and tags. 

Currently, the generic tag is largely geared towards imperative C++-like languages. I have been attempting to implement support for Haskell, and I have found that Haskell uses almost none of the commands defined in generic.

Furthermore, while groups of features can be modularly defined using tags, the functions used by all code tags are declared in a single monolithic class in code.py.

I suggest that we move towards a convention where the Python file which declares methods is stored next to the .talon file which uses them, which is already the convention used by the concrete implementations of programming languages.

- [x] Break up code.py into one file per tag and move them into `lang/tags/` 
      PR #652)
- [x] Break up existing tags into more fine grained sets of features
      PR  #656 (WIP)

**Comment by pokey** [comment]
@wenkokke can we close this now?

**Comment by wenkokke** [comment]
Fixed in #656.
