### ISSUE TITLE
Command history records all speech while talon is asleep

### ISSUE THREAD

**Issue by SCdF** [knausj85/knausj_talon#660]
To reproduce:
- open command history (say "command history")
- sleep talon however you do this (ie "talon sleep")
- say random things

What I would expect: the random things I say don't get recorded by command history, because they are not commands.

What happens: the random things I say are recorded by command history

I'm not sure why this occurs, but I'm somewhat sure it didn't use to do this.

**Comment by knausj85** [comment]
It's a result of this:

https://github.com/knausj85/knausj_talon/blob/516c905ba9848b0f441f9a733536eee2e243412f/modes/sleep_mode_wav2letter.talon#L6

**Comment by AndreasArvidsson** [comment]
Just add this to the phrase callback
```
if not actions.speech.enabled():
        return
```

**Comment by rntz** [comment]
I actually prefer this, as it lets me see what went wrong if a wake-up command was misinterpreted. But we could definitely turn it off by default if that is a more common preference.

**Comment by rntz** [comment]
Yeah, most people seem to want the history to ignore things in sleep mode so I think it's fine.
