### ISSUE TITLE
make java.talon use 'funky' instead of method or otherwise make them consistent

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#662]
https://github.com/knausj85/knausj_talon/blob/4ba1efb261a810c103ada8135cd765ac4213514b/lang/java/java.talon#L48

**Comment by splondike** [comment]
@michaelpog FYI, this change is probably going to happen in #656 . What will happen with that is that all the commands using the word 'method' will use 'funky' instead (making Java consistent with all the other languages). Aside from that the commands should be the same. So for example ^pro static method <user.text>$ becomes ^pro static funky <user.text>$
