### ISSUE TITLE
'allcaps that' not working with umlauts

### ISSUE THREAD

**Issue by timo95** [knausj85/knausj_talon#673]
1. select ü in some editor field
2. 'allcaps that'
3. result is ' ' instead of 'Ü'

This is probably not the only case where umlauts don't work. This might have to be solved in talon itself, but I decided to open the issue here first.

**Comment by timo95** [comment]
I just found regex string that might be the cause: https://github.com/knausj85/knausj_talon/blob/182b28bb04494f55481003539536305e160295a3/code/formatters.py#L291

Using `\w` instead might be the solution.

**Comment by rntz** [comment]
Fixed by https://github.com/knausj85/knausj_talon/commit/1e4512b4eb79013b45692115ce7655e94ffaf4bd
