### ISSUE TITLE
guide says it uses 'tab new' but it seems 'tab open' is right

### ISSUE THREAD

**Issue by somanythings** [knausj85/knausj_talon#689]
https://chaosparrot.github.io/talon_practice/lessons/browser.html says 'tab new' for a new tab, but looking at the code, it's tab open

**Comment by splondike** [comment]
@somanythings Both tab open and tab new are mapped to the same thing, see https://github.com/knausj85/knausj_talon/blob/master/misc/tabs.talon#L3 .

Also that project is downstream of this one, so you'd probably want to submit issues against its tracker instead: https://github.com/chaosparrot/talon_practice/issues

**Comment by somanythings** [comment]
thanks for that @splondike , I swear last night "tab open" kept being heard as "tab one", but it's doing fine now. 🤷‍♂️
