### ISSUE TITLE
windows has dpi issues with help windows

### ISSUE THREAD

**Issue by somanythings** [knausj85/knausj_talon#692]
this might be in the wrong place, apologies if it is. 

windows 11

I have a 3k 15" screen on this laptop.  **3840x2160**
![image](https://user-images.githubusercontent.com/6841417/145191136-19deb325-1c41-4565-bc05-3273b742d13b.png)
it might not be obvious in this screenshot but the help functions are very small

here it is on the bigger screen 32" **3840x1600** where it looks fine
![image](https://user-images.githubusercontent.com/6841417/145191345-c3e2ac4c-b0d4-49c5-a998-15903675ee21.png)

**Comment by AndreasArvidsson** [comment]
There is a `imgui.scale` setting in settings.talon, just increase that.

**Comment by timo** [comment]
we should probably make sure the existence of this setting is also pointed out in the talon wiki, with a brief mention that knausj already has it in its settings.talon, but also a word or two on how to set it manually?

**Comment by somanythings** [comment]
> There is a `imgui.scale` setting in settings.talon, just increase that.
> 
> You can use host name as a context/header match to have different settings on different computers.

Thanks @AndreasArvidsson at a glance, that looks like it's global will that just make it HUGE on the big monitor? 
presumably windows exposes something because it gets right across monitors.

**Comment by splondike** [comment]
This is a Talon+Windows/Linux issue: https://github.com/talonvoice/talon/issues/262 . I'm not sure we can do much on our side apart from mentioning this workaround in the wiki as timo suggested. I've added it to my list of TODOs for the wiki :).

I imagine it would make it huge on the lower DPI monitor unfortunately :(.
