### ISSUE TITLE
"snap top left third" is snapping to the entire top left quarter

### ISSUE THREAD

**Issue by nathanheffley** [knausj85/knausj_talon#704]
I have no problem using all of the snap positions, except for the "top left third" position. All of the other third positions work fine including the other corners, but whenever I try to do the top left third it ends up taking the entire top left quarter of my screen. I have no trouble getting Talon to transcribe top left third accurately and the recordings show that it's recording top left third, but every single time it ends up moving my window to be the entire top left quarter.

Nothing is showing up in the logs when I use this command either, it works except for the size difference. I'll dig into him more to more and see if I can finder reason this might be happening and if it requires a PR.

**Comment by rntz** [comment]
That's strange but I can think of one reason it might happen. There are two ways for talon to parse that phrase:

- "snap top left third", the command we want
- "snap top left" (snaps to top-left half) "third" (do that three times)

Try running `sim("snap top left third")` in the reply. I think there's also some debug command that does the same thing, it might be `talon debug last` - so, say `snap top left third` and then wait for it to recognize, then say `talon debug last` and look at the log.

**Comment by rntz** [comment]
Oh, actually, I can think of another reason. The "snap top left third" command was only added recently (it had been left out by accident), so make sure you have an up to date knausj. Otherwise "snap top left" "third" will be the ONLY way talon could interpret that command.

**Comment by nathanheffley** [comment]
Oh wow I didn't even think about it being added recently because I only installed this earlier this week and the top right third worked, with the newest version it works great. Thanks!
