### ISSUE TITLE
Deduplicate JavaScript and TypeScript actions

### ISSUE THREAD

**Issue by auscompgeek** [knausj85/knausj_talon#715]
There's a lot of code duplication between JavaScript and TypeScript. This is error prone, and inconsistencies are easy to miss, for example the bugfix in #714 after a refactor.

Given that TypeScript can, for the most part, be considered a superset of JavaScript syntax, I'd like to propose combining the code in some way.

We could add a tag, move the existing JS actions to be active under that tag, and activate that tag in both JS and TS languages.

Alternatively, we could go all in and replace the modes with tags (#603), but this might be a good stepping stone?

**Comment by pokey** [comment]
Yeah I'd lean towards @AndreasArvidsson's [solution](https://github.com/knausj85/knausj_talon/issues/603#issuecomment-980106400) for this one
