### ISSUE TITLE
Mintty  not  detected (windows)

### ISSUE THREAD

**Issue by ebundy** [knausj85/knausj_talon#717]
Hello, 

I don't understand why  mintty.py doesn't recognize the mintty application : actions are not available
while it's working for other terminals like cmd.

I tried  other variants in the mod.apps.mintty  part  but no success : 

```
mod.apps.mintty = """
os: windows
and app.name: Terminal
os: windows
and app.name: mintty.exe
os: windows
and app.name: git-bash.exe
os: windows
and title: MINGW64
"""
```

Do you have an idea or do you know  how to increase the logging level in  talon ?

**Comment by rntz** [comment]
Try using the command "talon copy context pie" while you have mintty focused, iirc that should copy some Python code to your clipboard that should match it.

**Comment by rntz** [comment]
If it works, paste the results here as well and someone can probably update the file in knausj, or you can make a PR yourself.

**Comment by ebundy** [comment]
> If it works, paste the results here as well and someone can probably update the file in knausj, or you can make a PR yourself.

Hello rntz,

Thank you for your suggestion.
 I tried but it didn't work.
 whatever I manage to make it working  by fixing my regex : 

```
mod = Module()
mod.apps.mintty = """
os: windows
and title: /MINGW64/
"""
```
It is just a  workaround,  so I'm not sure if it makes sense to propagate it.
