### ISSUE TITLE
auto_insert is documented to call auto_format

### ISSUE THREAD

**Issue by lunixbochs** [knausj85/knausj_talon#725]
I understand if you want to override `auto_insert` too because you're adjusting the cursor position afterwards, but the general intention is for `auto_format` to do text formatting

I think the dictation `auto_insert()` implementation should potentially first `text = auto_format(text)` (which is the identity function by default) as per the docstring:
```
auto_insert(text: str)
  Insert text at the current cursor position, automatically formatting it using actions.auto_format(text)
```

https://github.com/knausj85/knausj_talon/blob/master/code/dictation.py#L401

**Comment by wolfmanstout** [comment]
This apparently dates back to context sensitive dictation, which moves the cursor around and selects text to figure out the surrounding context. Even without this, dictation context is stateful, and prior to context sensitive dictation, so was user.auto_format. Hence, to achieve this we would need to separate the contextual formatting from auto_format and possibly even the stateful formatting if we want auto_format to be stateless. The latter would be particularly difficult considering how the DictationFormat object uses state extensively. Considering all that, do you think this would be a change for the better or would you suggest another approach? We could also simply re-implement auto_format to use a fresh DictationFormat object, which would provide approximately the same behavior, but would not exactly match the auto_insert docs.

@rntz (added support for context sensitive dictation)

**Comment by rntz** [comment]
I think what aegis was suggesting was not that we try to move all of our dictation formatting into auto_format, which would be difficult for the reasons you give, but rather that the first thing we should do in auto_insert should be to call auto_format, so that if the user overrides it their auto formatting will get applied. This should be a simple fix.

**Comment by wolfmanstout** [comment]
Ah okay, that would indeed be a simple fix as long as we are okay then letting auto_insert do its thing afterward, potentially overriding some of what the user's auto_format did.

**Comment by rntz** [comment]
Ok, #740 should address this. I wouldn't mind getting some clarification from @lunixbochs about whether auto_format is intended to be stateful/aware of surrounding text context or not. Perhaps this should go into its documentation. I've been assuming that it should be stateless, which makes it not very useful for dictation auto-formatting.

**Comment by rntz** [comment]
Reopen if you think that we should be doing something different than just calling auto_format and then doing our own dictation auto-formatting on the result.
