### ISSUE TITLE
find better name for function_gui

### ISSUE THREAD

**Issue by DonnerWolfBach** [knausj85/knausj_talon#732]
While commands defined in the [functions_gui.talon](https://github.com/knausj85/knausj_talon/blob/master/lang/tags/functions_gui.talon) file provide easier access to common functions (e.g. print,len or int in python) the file name seems very unintuitive to me. 

I propose renaming this and any connected file to "common_functions.talon/py" or something similar.

**Comment by pokey** [comment]
This sounds like a good idea. While we're here we should probably rename the tag and a couple relevant captures etc

- `code_functions_gui` tag => `code_common_functions`
- `user.code_toggle_functions` action => `code_toggle_common_functions_gui`
- `<user.code_functions>` => `<user.code_common_function>`
