### ISSUE TITLE
Support chaining keywords in programming languages

### ISSUE THREAD

**Issue by pokey** [knausj85/knausj_talon#807]
## The goal

I have a [commit](https://github.com/pokey/pokey_talon/commit/aab118daa6f027e67a1075f025b7869ffde64168) on my repo that enables me to chain programming language keywords, for example `"state return null"` or `"state export default const"` , instead of `"state return state null"` or `"state export state default state const"`.  I’m trying to figure out how to reconcile this setup with @wenkokke’s fine-grained tags [commit](https://github.com/knausj85/knausj_talon/commit/73d94794bcb330374f18432b0f9f2af35082849c).

## How it works on my branch

Here are the important parts of my commit:

We first define a list and an action for keywords:
https://github.com/knausj85/knausj_talon/blob/aab118daa6f027e67a1075f025b7869ffde64168/code/keywords.py#L4-L12

Then define a spoken form that allows "state" followed by one or more keywords:
https://github.com/knausj85/knausj_talon/blob/aab118daa6f027e67a1075f025b7869ffde64168/lang/programming.talon#L33

Then each language defines its keywords, including spacing around them.  See eg Typescript:
https://github.com/knausj85/knausj_talon/blob/aab118daa6f027e67a1075f025b7869ffde64168/lang/typescript/typescript.py#L50-L77

## The problems

There’s kind of two problems to solve:

### Many tags

The first is how we handle the fact that after @wenkokke’s commit, these keywords are now spread across many tags. 
 We would somehow need to define the lists in all the separate tags, then merge all of them together in a capture or something?

### Actions vs lists
The other problem is that I just use a list of strings to insert, whereas in knausj they are actions.  The latter is a bit more flexible, but I’m not sure how to reconcile that with my approach

**Comment by wenkokke** [comment]
We could adopt my suggestion of giving each root tag, like op, a unique prefix, e.g., “op”?

**Comment by pokey** [comment]
@wenkokke sorry I'm not sure I understand.  Could you please elaborate?

**Comment by pokey** [comment]
I also think there's a related point around being able to both write simple keywords, and to build more complex expressions.  Eg I might want to just output `if `, or I might want to insert an `if` statement.  The latter should be an action so that I can eg override it to use snippets.  Maybe the former could just be a list, and allow chaining?
