### ISSUE TITLE
Missing explicit voice command to write private function

### ISSUE THREAD

**Issue by auscompgeek** [knausj85/knausj_talon#825]
Currently the only way to call `code_private_function` is indirectly via `code_default_function` (except for R).

This poses a few problems:

- Python and Scala override `code_default_function` to call `code_public_function`. This currently makes it impossible to use their `code_private_function` implementations without adding a custom voice command.
- The Java implementation of `code_protected_function` creates a method without any modifiers, which is confusing.
  - It _should_ insert the `protected` access modifier, but then there would be no way to insert a method with no access modifiers (i.e. a package-private method, distinct from `protected`).
  - As a workaround, one can say `state protected`, pause, then `pro funky ...`, but this is clearly inconsistent and disrupts the flow.

I would like to propose the following:

- a new `private funky <text>` command, which calls `code_private_function`
- a new action `code_default_static_function`, to be called by `static funky <text>`, can default to calling `code_private_static_function`
- a new `private static funky <text>` command, to replace current usage of `static funky <text>`

This would allow for:

- Java: creating methods with all possible access modifiers (including package-private and `protected`) using the commands in `functions.talon`
- TypeScript: creating functions outside methods, whilst still being able to create private methods (see also #824)
- Python/Scala: actually creating private functions

**Comment by splondike** [comment]
This sounds good to me.

**Comment by pokey** [comment]
What might be nice is the following:

```talon
{user.function_modifier}+ funky <user.text>: user.code_function(function_modifier_list, text)
```

Then there could be a default implementation

```py
    def code_function(modifier_list: list[str], text: str):
        """Inserts function declaration"""
        formatted_text = actions.user.formatted_text(
            text, settings.get("user.code_function_formatter")
        )
        modifier_string = " ".join(modifier_list)
    
        result = f"{modifier_string} function {formatted_text}"

        actions.user.code_insert_function(result, None)
```

Individual languages could then override the implementation to look at `modifier_list` and choose a different formatter / use different template for the function

Definitely a different approach, but figured I'd throw it out there.  

It is related to #807

**Comment by splondike** [comment]
I actually really like pokey's suggestion. It opens this up to more keywords like async, and even putting in return types depending on the language. To facilitate all that we'd probably make function_modifier a capture instead of a list.

The complexity of the extra abstraction could be offset by defining a 'standard' way of ordering modifiers as well as a standard list of command words. Something like this in the .talon file:

```
# This command is used for inserting a function definition with modifiers (e.g. private, protected, async) or return types.
# Since this gives a lot of flexibility, it could also make usage vary unnecessarily between programming languages.
# To encourage consistency consider the following guidelines:
#
# * Use these names for modifier labels: pro -> protected, pub -> public, static, private, async
# * The order of modifiers should be this: visibility (private, pro), other (static, async), return type (int, bool).
#
# So with the above in Java you might be able to say 'private static void funky hello world' to get 'private static void helloWorld()'
```

**Comment by auscompgeek** [comment]
Another bonus would be removing irrelevant commands from the grammar, which should theoretically improve recognition. I'm on board.

**Comment by pokey** [comment]
> The complexity of the extra abstraction could be offset by defining a 'standard' way of ordering modifiers

Not sure I follow. If we use a `+` after the list (or capture), then the order shouldn't matter

**Comment by splondike** [comment]
Yeah, if we use the + that would be true. We probably don't need the comments about ordering in that case.

**Comment by splondike** [comment]
This should be covered off by #879 . Closing issue.
