### ISSUE TITLE
How to add CSV files with additional vocabulary?

### ISSUE THREAD

**Issue by mostlyjason** [knausj85/knausj_talon#832]
I would like to add additional vocabulary, but I can't find a way to do that looking at the README. I searched the code and came across vocabulary.py which seems to load from a CSV file. However, I can't find any description of the expected format or where I should put the file. Can someone provide an example? Bonus points to document this in the project README. If this already exists and I missed it I apologize.

**Comment by auscompgeek** [comment]
You probably want `settings/additional_words.csv` in your knausj_talon folder? The format should be self-explanatory from the default contents.

**Comment by mostlyjason** [comment]
@auscompgeek thanks I didn't see that initially! Documenting it so its easier to find
