### ISSUE TITLE
using `recent repeat <number_small>` throws off the `scratch that` command

### ISSUE THREAD

**Issue by tararoys** [knausj85/knausj_talon#843]
The `recent repeat <number_small>` command allows you to pick a phrase you said off the recent list and retype it.  

When you have the recent list open, and using the command `recent repeat <number` to type out a previous command, the repeated command is not added to the top of recent list.  This throws off the stack used for the command `scratch that`, making the `scratch that` command incorrect, since  `Scratch that` uses the character count of the phrase on top of the recent list stack to delete the last utterance.  

In order for the `scratch that` command to work as expected, the recent repeat command needs to put the repeated phrase back at the top of the recent repeat list.

**Comment by rntz** [comment]
I think this was fixed by your PR, so I'm going to close it.
