### ISSUE TITLE
formatter accuracy

### ISSUE THREAD

**Issue by lunixbochs** [knausj85/knausj_talon#851]
This has come up a couple of times. I suspect you'll improve formatter accuracy if you make these changes:

"allcaps" -> "all cap"
"alldown" -> "all down"

The reason for this is e.g. "alldown" is not an english word, D sounds like T, so "alld" sounds like alt, and you get "alt down".
Same for allcaps. Allc sounds a bit like alt, and you get "alt cap".

allcaps has a second problem. If you say "allcaps something", the S S (cap(s s)omething) chain will blend together in your speech and you'll get something that might sound more like "alt cap something". Hence removing the S.

**Comment by pokey** [comment]
I would be tempted to leave this one where @rntz left it, with "all caps", because I'd worry "all cap" would lead to some accuracy issues wrt "alt cap".  Shall we close this one out?

**Comment by lunixbochs** [comment]
it's the other way around! binding it as `all caps` can cause misrecognitions of `alt cap` when you say a word starting with an s, because it's human nature to collapse a double-s, e.g. try saying "all caps something" out loud quickly.

**Comment by pokey** [comment]
ahh ok yeah. For some reason it made more sense the second time you said it 🤷‍♂️😄

do we want to keep "all caps" as a synonym?  @lunixbochs in your testing did you try saying "all caps" when the term was mapped as "all cap", or just tried "all cap"?

**Comment by lunixbochs** [comment]
I did test saying "all caps" when it was bound as "all cap" and it worked, still better than when only "allcaps" was bound.

A possible issue with binding both, is now you may have a problem of homophones that only differentiate by whether the word starts with an `s`.

I would suggest just binding "all cap" and re-evaluate if new complaints surface. We're still likely going to be much better off than the old "allcaps" command.

**Comment by pokey** [comment]
All makes sense to me.  Opened #861 to finish addressing this issue
