### ISSUE TITLE
Consider moving the default branch to "main"

### ISSUE THREAD

**Issue by phillco** [knausj85/knausj_talon#874]
In addition to the inclusive language benefits, I think at this point there's an argument to be made for consistency/momentum/ simplicity -- more and more repositories are moving to `main`, including the following Talon related ones:

- https://github.com/cursorless-dev/cursorless
- https://github.com/cursorless-dev/cursorless-talon
- https://github.com/david-tejada/rango
- https://github.com/phillco/talon-axkit

My personal motivation is that when merging up my forks of repositories, I have to think about whether it's `git merge upstream/master` vs `git merge upstream/main`, and so I'd prefer to just move as many to `main`as I can :)

GitHub also now publishes a helpful popover to aid people in migrating their local checkouts, so that should hopefully help with the migration:

<img width="642" alt="Screen Shot 2022-06-03 at 1 10 28 PM" src="https://user-images.githubusercontent.com/536668/171943715-a8c0a012-b214-47a3-bace-f3fe189cca14.png">

**Comment by pokey** [comment]
I'll add that GitHub makes it completely painless for users. Cursorless switched from `master` to `main` fairly late in the game and we had zero complaints from users. It keeps all the old endpoints active, but also shows a little message that user can easily copy-paste into terminal to migrate if they'd like to

**Comment by phillco** [comment]
I don't think it's as painless as their repository renaming support (which work seamlessly; here the user still has to run a block of commands locally), but it's hopefully not too bad.

**Comment by pokey** [comment]
Nope those local commands are totally optional

**Comment by phillco** [comment]
Oh! TIL. OK then, guess no reason not to do it :)

**Comment by knausj85** [comment]
*rolls dice* It's done

**Comment by phillco** [comment]
Wow, nice! Thanks @knausj85!

**Comment by phillco** [comment]
FWIW, I did have to run the GitHub-recommended commands in my existing clone, as I got this initially:

```
$ git pull
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 356 bytes | 118.00 KiB/s, done.
From github.com:knausj85/knausj_talon
   3184687c..f7ab08d1  knausj-personal-experiments -> upstream/knausj-personal-experiments
 * [new branch]        main                        -> upstream/main
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

**Comment by pokey** [comment]
Huh that's odd. I wonder if it depends how you have things set up locally?
