### ISSUE TITLE
pre-commit (`shed`) doesn't work on Windows for files with unicode in them

### ISSUE THREAD

**Issue by phillco** [knausj85/knausj_talon#875]
Quoteth @wolfmanstout:

> Basically what I'm seeing is that on Windows shed skips formatting of dictation.py because of the unicode present in the file:  `"skipping 'code/dictation.py' due to 'charmap' codec can't decode byte 0x9d in position 3481: character maps to <undefined>"`. There's nothing wrong with `dictation.py` -- it's legal to assume utf8 encoding in Python ... but the Windows default behavior for `open()` is to use the platform-default encoding instead of utf8. On windows that's `"cp1252"`. This is apparently what shed, or one of its tools, relies on.

> It's easy to repro without shed by simply opening the file and doing `f.read()` -- this only works if I include `encoding="utf8"` in the `open()` call, otherwise it gives the same charmap error. Like I said, I'm not sure what the best fix for this is. Ideally, there would be some flag to shed to specify the encoding in the pre-commit yaml config. Failing that, I suppose we could replace all the unicode chars in dictation.py with escapes such as `\u201d` instead of `”`. It's fairly easy to get these using python: `hex(ord("”"))`, which prints `0x201d`. This hurts readability but it would make the file ASCII compatible.

> Hope that's helpful.... sorry for the drive-by comment here but I figured better to speak up soon in case others bump into this! I noticed this when I was merging in the changes, because I saw that this file was still not black-formatted despite running pre-commit (I was following a process similar to pokey, and found this at the step where I run pre-commit on my own code).

**Comment by phillco** [comment]
Cool, I can reproduce it :)

<img width="1199" alt="Screen Shot 2022-06-03 at 4 49 25 PM" src="https://user-images.githubusercontent.com/536668/171967670-81718b77-2890-4527-9ad7-9cc4bbba4817.png">

**Comment by phillco** [comment]
Good news! This was fixed in the root project: https://github.com/Zac-HD/shed/commit/a757277a3ca282769fd7a60a8a844c4a87f68d00, v`0.10.1`.

Hopefully this will make it to our pre commit hooks soon.

**Comment by wolfmanstout** [comment]
This issue is resolved, woo-hoo! I see some minor differences between what shed produces locally vs. remotely. I also had to run pre-commit multiple times for shed to apply all its changes and it only said PASSED on the third run. I guess it's possible those are differences between shed 0.10.0 and 0.10.1. I'll follow up with you on that.

**Comment by auscompgeek** [comment]
I think we can close this now with #882
