### ISSUE TITLE
.talon file auto formatter

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#909]
Now that we have pre-commit hooks set up, it would be nice if we had a talon file auto formatter. The minimal feature set here is consistent indentation. I'd vote for 2 or 4 spaces.

I know @AndreasArvidsson has one of these, albeit in VScode rather than standalone. His also auto-aligns the right-hand-sides of all single-line commands in the whole file, which is nice for scannability but could result in very large diffs if that alignment needs to change. We could either disable this feature or try to tame it, eg, always align to column 36 and break lines whose LHS is too long for that.

I worry a bit about parsing .talon files correctly - it's a pretty simple format, but if we get it wrong the autoformatter will break stuff.

See also: #900 #666

**Comment by rntz** [comment]
It would also be useful to warn about problems in spoken forms, eg. literal numbers in spoken forms (#901).

**Comment by AndreasArvidsson** [comment]
@rntz My talon script formatter is now updated with a fixed column width of 24. Those git diffs was really starting to bug me so it  was about time.

**Comment by wenkokke** [comment]
@rntz It should be rather easy to write a python script that uses my talon parser (https://github.com/wenkokke/tree-sitter-talon) to do some basic linting such as non-alphabetic numbers and spoken forms when not specifying a different engine.

It should also be pretty simple to write a pretty printer from those syntax trees.

**Comment by wenkokke** [comment]
@rntz I've made good on my threats and wrote a little Talon file formatter: [wenkokke/talonfmt](https://github.com/wenkokke/talonfmt)

**Comment by wenkokke** [comment]
> It would also be useful to warn about problems in spoken forms, eg. literal numbers in spoken forms (#901).

Unfortunately, this isn't necessarily a problem in files which set the speech-engine option, so it's not trivial to check, but you could easily add this as a lint on the formatter, since it parses the full file into an AST.

**Comment by wenkokke** [comment]
@phillco Would you be able to help me setup `talonfmt` with precommit, so we can use it on this repository?

**Comment by pokey** [comment]
@wenkokke https://pre-commit.com/index.html#creating-new-hooks

**Comment by wenkokke** [comment]
On it. Broke some tests while doing it somehow.

**Comment by auscompgeek** [comment]
Done in #947.
