### ISSUE TITLE
Inconsistent function names/descriptions in operators_assignment.py and operators_assignment.talon

### ISSUE THREAD

**Issue by chrisnicollo** [knausj85/knausj_talon#920]
For some of the bitwise operator assignment functions, their names end in “equals” in operators_assignment.talon and in “assignment” in operators_assignment.py. It seems like the convention here is “assignment” and that the function names ending in “equals“ should be changed to end with “assignment” instead. Additionally, some of the doc comments in operators_assignment.py do not match the name of their function, as with function ‘code_operator_subtraction_assignment’ and its comment “””code_operator_subtraction_equals”””

**Comment by pokey** [comment]
I believe this issue was addressed by #920
