### ISSUE TITLE
what do we want to keep in CI?

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#925]
Applying pyupgrade in CI caused serious breakage ('say' and dictation and formatters not working): #922.

We've temporarily fixed this by removing shed from CI: #923.

Long term we probably want to add back some of what we removed. Which things and with what options?

**Comment by phillco** [comment]
FYI @pokey - you might want to make a similar change to cursorless-talon

**Comment by rntz** [comment]
Closing this as I think we've settled on a reasonably stable configuration after disaggregating what used to be bundled into shed. Reopen for further discussion.
