### ISSUE TITLE
vscode jupyter commands out of date

### ISSUE THREAD

**Issue by zilch42** [knausj85/knausj_talon#983]
Hi there, 
I believe the jupyter notebook commands in VScode have changed. The following commands in `vscode.talon` have been depreciated and no longer work:

```
# jupyter
cell next: user.vscode("jupyter.gotoNextCellInFile")
cell last: user.vscode("jupyter.gotoPrevCellInFile")
cell run above: user.vscode("jupyter.runallcellsabove.palette")
cell run: user.vscode("jupyter.runcurrentcell")
```

I believe these are now the correct commands:
```
# jupyter
cell next: user.vscode("notebook.focusNextEditor")
cell last: user.vscode("notebook.focusPreviousEditor")
cell run above: user.vscode("notebook.cell.executeCellsAbove")
cell run: user.vscode("notebook.cell.execute")
```

**Comment by pokey** [comment]
This would also be a nice easy PR!  Happy to take it for a spin locally to confirm it works as expected if you file a PR

**Comment by zilch42** [comment]
It would, you're right. I need to learn how to do pull requests and this is the perfect opportunity. Leave it with me and I'll submit something, probably monday.
